### ISSUE TITLE
shape inference error

### ISSUE THREAD

**Issue by LucQueen** [llvm/torch-mlir#1034]
I try to support chunk op following this patch,
https://github.com/llvm/torch-mlir/pull/820/files#diff-764dc1609912e4f2026cf4deb040ff11873c4ebebaa8e4ba96bc93812472fe26
but i get a error like this
```
File "/mnt/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 179, in compile
    run_pipeline_with_repro_report(mb.module,
  File "/mnt/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 49, in run_pipeline_with_repro_report
    raise Exception(f"""
Exception:
Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: 'torch.shape.calculate.yield.shapes' op operand #0 must be Int list type (int[]) of Torch IntType values, but got '!torch.list<list<int>>'
note: see current operation: "torch.shape.calculate.yield.shapes"(%1641) : (!torch.list<list<int>>) -> ()
```
when I translate transformer to mlir
```
import torch
transformer = torch.nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
inputs = [src, tgt]
transformer.train(False)
module = torch_mlir.compile(transformer, inputs, output_type=torch_mlir.OutputType.LINALG_ON_TENSORS, use_tracing=True)
backend = refbackend.RefBackendLinalgOnTensorsBackend()
compiled = backend.compile(module)
```
thanks for answering me！

**Comment by LucQueen** [comment]
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    module = torch_mlir.compile(transformer, inputs, output_type=torch_mlir.OutputType.LINALG_ON_TENSORS, use_tracing=True)
  File "/mnt/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 144, in compile
    mb.import_module(scripted._c, class_annotator)
RuntimeError: layout_impl is only implemented for TensorImpl subclasses.
```
@ramiro050  when I use #1022 , i got this error, and this is env
Package            Version
------------------ ----------------------
certifi            2022.6.15
charset-normalizer 2.1.0
cmake              3.22.5
gitdb              4.0.9
GitPython          3.1.27
idna               3.3
ninja              1.10.2.3
numpy              1.23.1
Pillow             9.2.0
pip                22.1.2
pkg_resources      0.0.0
pybind11           2.9.2
requests           2.28.1
setuptools         44.0.0
smmap              5.0.0
torch              1.13.0.dev20220704+cpu
torchvision        0.14.0.dev20220706+cpu
typing_extensions  4.3.0
urllib3            1.26.10
wheel              0.37.1

any problem? thanks

**Comment by LucQueen** [comment]
```
  File "/mnt/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 179, in compile
    run_pipeline_with_repro_report(mb.module,
  File "/mnt/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 49, in run_pipeline_with_repro_report
    raise Exception(f"""
Exception:
Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.chunk' that was explicitly marked illegal
note: see current operation: %35 = "torch.aten.chunk"(%34, %12, %13) : (!torch.tensor<[10,32,1536],f32>, !torch.int, !torch.int) -> !torch.list<tensor>


Error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline' /tmp/Transformer.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

```
import torch
import torch_mlir
from torch_mlir_e2e_test.linalg_on_tensors_backends import refbackend

transformer = torch.nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
inputs = [src, tgt]
transformer.train(False)
module = torch_mlir.compile(transformer, inputs, output_type=torch_mlir.OutputType.LINALG_ON_TENSORS, use_tracing=True)
backend = refbackend.RefBackendLinalgOnTensorsBackend()
compiled = backend.compile(module)
```
meet another error about chunk, when I use #1022 @ramiro050

**Comment by LucQueen** [comment]
```
import torch
import torch_mlir
from torch_mlir_e2e_test.linalg_on_tensors_backends import refbackend

class ChunkModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        chunks = 4
        dim = 0
        splits = torch.ops.aten.chunk(x.view(10), chunks, dim)
        return splits[0], splits[1], splits[2], splits[3]

chunk = ChunkModule()
chunk.train(False)
inputs = torch.rand(10)
module = torch_mlir.compile(chunk, inputs, output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)
backend = refbackend.RefBackendLinalgOnTensorsBackend()
compiled = backend.compile(module)
```
```
Exception:
Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.chunk' that was explicitly marked illegal
note: see current operation: %10 = "torch.aten.chunk"(%9, %2, %3) : (!torch.tensor, !torch.int, !torch.int) -> !torch.list<tensor>


Error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline' /tmp/ChunkModule.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by ramiro050** [comment]
> meet another error about chunk, when I use https://github.com/llvm/torch-mlir/pull/1022 @ramiro050

The PR is not yet in a working state.
