### ISSUE TITLE
Cannot export model with torch.arange

### ISSUE THREAD

**Issue by harsh-nod** [llvm/torch-mlir#106]
Below is a simple python script that reproduces the issue.

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch_mlir

torch_mlir.debug_trace_to_stderr()

N = 3
Cin = 16
Cout = 4
w = 10
h = 10

class Net(nn.Module):
    def __init__(self, Cin, Cout):
      super(Net, self).__init__()
      self.conv1 = nn.Conv2d(Cin, Cout, (3,3))
    def forward(self, x):
      x = self.conv1(x)
      indices = torch.arange(N)
      x = x[indices, :, :, :]
      output = F.log_softmax(x, dim=1)
      return output

model = Net(Cin, Cout)
inputs = torch.ones((N,Cin,h,w))
loss = torch.nn.NLLLoss()
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, Cout)

mb = torch_mlir.ModuleBuilder()
with mb.capture_function("arange_test", [inputs, target]) as f:
  result = loss(model(inputs), target)
  result.backward()
  f.returns([result] + [p.grad for p in model.parameters()])
mb.module.operation.print(large_elements_limit=2)
```

When I try to run this, I get the following output.
```
TORCH_MLIR TRACE: Convolution (unboxed) dispatch: aten::convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups) -> (Tensor)
TORCH_MLIR TRACE: Fallback (boxed) dispatch: aten::arange.start_out(Scalar start, Scalar end, Scalar step=1, *, Tensor(a!) out) -> (Tensor(a!))
Traceback (most recent call last):
  File "models/conv2d.py", line 32, in <module>
    result = loss(model(inputs), target)
  File "/pytorch_nightly/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "models/conv2d.py", line 20, in forward
    indices = torch.arange(N)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::arange.start_out.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, PrivateUse2, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2154 [kernel]
PrivateUse2: registered at /mlir-npcomp/frontends/pytorch/csrc/c10_dispatch/acap_dispatch.cpp:645 [backend fallback]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:8628 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_1.cpp:10219 [kernel]
Autocast: fallthrough registered at /pytorch/aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:527 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

The error states that there is no fallback kernel defined for this op (arange.start_out). But I noticed that in type_dispatch/aten_mlir_type_default.cpp there is a function RegisterAtenTypeFunctions that registers arange.start_out

```C++
          .op(torch::RegisterOperators::options()
                  .schema("aten::arange.start_out(Scalar start, Scalar end, "
                          "Scalar step=1, *, Tensor(a!) out) -> Tensor(a!)")
                  .impl_unboxedOnlyKernel<at::Tensor &(at::Tensor &, at::Scalar,
                                                       at::Scalar, at::Scalar),
                                          &ATenMLIRTypeDefault::arange_out>(
                      at::TensorTypeId::XLATensorId)
                  .aliasAnalysis(c10::AliasAnalysisKind::FROM_SCHEMA))
``` 

But the error also states that I passed in an empty list of Tensors. Does that mean we need another definition of this op or just how it handles optional arguments because I have only passed in the end argument in the above function? Or do you think the root cause of this is something completely different?

**Comment by harsh-nod** [comment]
I came up a simpler test case.

```python
import torch
import torch_mlir

torch_mlir.debug_trace_to_stderr()

mb = torch_mlir.ModuleBuilder()
N = 10
with mb.capture_function("arange_test", []) as f:
    x = torch.arange(N)
    f.returns([x])
```

It seems that even though the dispatch is going to the fallback kernel, when in the dispatcher::callBoxed function, the dispatchKey is c10::DispatchKey::Undefined which means that pytorch is unable to find a boxed implementation for this op. It seems like we might have to implement this op just like you implemented the copyUnderKernel. What do you think?

**Comment by stellaraccident** [comment]
Thanks - I believe that this gets routed to the "backendSelect" dispatch key, which is used for kernels that don't have tensor arguments (a heuristic on tensor arguments is what drives dispatch key selection). I know roughly what goes on there but this is the first I've run in to fixing it. I've got a version of PyTorch that dumps all of the dispatch metadata, which helps in these "where'd the kernel go" diagnoses. I just sent out/landed the other PRs and my queue is clear now. Let me take some time tomorrow to triage these (great!) test cases you've come up with.

**Comment by stellaraccident** [comment]
This appears to be a specific problem with kernels that have out parameters: aten::arange.start_out(Scalar start, Scalar end, Scalar step=1, *, Tensor(a!) out) -> (Tensor(a!))

The sequence on the stack is not as expected and something is getting inverted.

**Comment by stellaraccident** [comment]
Actually, looking at blame logs, may have been fixed two days ago (yay for procrastination). Rebasing and seeing...
