### ISSUE TITLE
Build and test on AArch64 Linux shows the following failure. 

### ISSUE THREAD

**Issue by u99127** [llvm/torch-mlir#1164]
Building and testing torch-mlir on AArch64 Linux hosts shows the following failure in the test suite. 

torch-mlir was built with the following parameters. 

```
cmake -GNinja -Bbuild \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DPython3_FIND_VIRTUALENV=ONLY \
      -DLLVM_ENABLE_PROJECTS=mlir \
      -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
      -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=`pwd` \
      -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=`pwd`/externals/llvm-external-projects/torch-mlir-dialects \
      -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
      -DLLVM_TARGETS_TO_BUILD=host \
      -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF \
       -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
      externals/llvm-project/llvm
```

```
******************** TEST 'TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py' FAILED ********************
Script:
--
: 'RUN: at line 11';   /media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/mlir_venv/bin/python3 /media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py | /media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/build/bin/torch-mlir-opt | FileCheck /media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py
--
Exit Code: 1

Command Output (stderr):
--
Traceback (most recent call last):
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py", line 39, in <module>
    test_module = TestModule()
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py", line 18, in __init__
    self.linear = torch.nn.quantized.Linear(5, 2, dtype=torch.qint8)
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/mlir_venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py", line 146, in __init__
    self._packed_params = LinearPackedParams(dtype)
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/mlir_venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py", line 24, in __init__
    self.set_weight_bias(wq, None)
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/mlir_venv/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py", line 29, in set_weight_bias
    self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
  File "/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/mlir_venv/lib/python3.8/site-packages/torch/_ops.py", line 164, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
/media/psf/Home/work/mlir-experiments/internal-new/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py:23:11: error: CHECK: expected string not found in input
 # CHECK: %[[SCALE:.*]] = torch.constant.float
          ^
<stdin>:1:1: note: scanning from here
module {
^

Input file: <stdin>

```

**Comment by silvasean** [comment]
It looks like your PyTorch is not built with quantization support, but this test uses the Torch quantization support. If we want to support this then we can configure the build system and lit so that the test says `REQUIRES: pytorch-quantization` and does not run this test when PyTorch is built without quantization.

**Comment by u99127** [comment]
Since I build pytorch from source using build_tools/libtorch.sh by choosing       -DTORCH_MLIR_USE_INSTALLED_PYTORCH=OFF  in the cmake configure above, perhaps the bug is in build_tools/libtorch.sh ?

I'm not sure about the difference between USE_PYTORCH_QNNPACK=ON + USE_QNNPACK=OFF in building pytorch.

**Comment by u99127** [comment]
Aha - the mystery clears - this might be a duplicate of https://github.com/llvm/torch-mlir/issues/1008 where we have this failing on AArch64 Linux and Apple Silicon Macs and thus something to do with PYTORCH_QNNPACK indeed. Sorry about the noise.
