### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wm901115nwpu** [llvm/torch-mlir#1184]
[720/1742] Generating Lazy Tensor Core IR Nodes
FAILED: tools/torch-mlir/generated_backend.hash tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/LazyNativeFunctions.cpp tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/RegisterLazy.cpp tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/shape_inference.cpp /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/generated_backend.hash /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/LazyNativeFunctions.cpp /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/RegisterLazy.cpp /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend/generated/shape_inference.cpp
cd /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/python/torch_mlir/csrc/base_lazy_backend && /Users/unicorn/miniconda3/envs/py38/bin/python3.8 /Users/unicorn/MyCodes/torch-mlir/build_tools/autogen_ltc_backend.py -b /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir
Traceback (most recent call last):
  File "/Users/unicorn/MyCodes/torch-mlir/build_tools/autogen_ltc_backend.py", line 504, in <module>
    main(args)
  File "/Users/unicorn/MyCodes/torch-mlir/build_tools/autogen_ltc_backend.py", line 465, in main
    generator()
  File "/Users/unicorn/MyCodes/torch-mlir/build_tools/autogen_ltc_backend.py", line 449, in __call__
    self.generate_shape_inference()
  File "/Users/unicorn/MyCodes/torch-mlir/build_tools/autogen_ltc_backend.py", line 309, in generate_shape_inference
    parsed_backend_yaml = parse_backend_yaml(
  File "/Users/unicorn/miniconda3/envs/py38/lib/python3.8/site-packages/torchgen/gen_backend_stubs.py", line 101, in parse_backend_yaml
    assert (
AssertionError: /Users/unicorn/MyCodes/torch-mlir/build/tools/torch-mlir/generated_native_functions.yaml contains unexpected keys: non_native. Only the following keys are supported: backend, class_name, cpp_namespace, extra_headers, supported, autograd, full_codegen
ninja: build stopped: subcommand failed.

**Comment by powderluv** [comment]
@henrytwo any thoughts ?

**Comment by henrytwo** [comment]
What version of PyTorch do you have installed? I suspect it might be out of date, since we made some modifications to the autogen library

Cc: @antoniojkim

**Comment by antoniojkim** [comment]
@wm901115nwpu You need to use the latest nightly PyTorch. It will not work with the 1.12 release. The non-native keyword is something that was added after the release 1.12 branch cut date.

**Comment by silvasean** [comment]
We've changed a lot about the LTC build. I'm closing this issue for now. Please file a new issue if you run into a new issue.
