### ISSUE TITLE
Torchdynamo tests fails with the llvm bump

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1664]
Hi, I'm working on the llvm-bump, I have added a patch (https://github.com/llvm/torch-mlir/pull/1654) that fixes all the issues except one. The issue is that the following 7 e2e tests are failing for the torchdynamo:      
 ```
    "BatchMlpLayerModule_basic", 
     "Mlp1LayerModule_basic", 
     "Mlp2LayerModuleNoBias_basic", 
     "Mlp2LayerModule_basic", 
     "MobilenetV3Module_basic", 
     "ResNet18Module_basic", 
     "ResNet18StaticModule_basic",
```
The error is as follows:
```
FAIL - "ResNet18StaticModule_basic"
        Runtime error: Traceback (most recent call last):
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 461, in call_user_compiler
            compiled_fn = self.compiler_fn(gm, self.example_inputs())
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 865, in debug_wrapper
            compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dynamo.py", line 60, in wrapper_backend
            user_callable = user_backend(dispatcher_ops, example_inputs)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/torchdynamo.py", line 35, in refbackend_torchdynamo_backend
            mlir_module = torch_mlir.compile(
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 366, in compile
            run_pipeline_with_repro_report(
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
            raise TorchMlirCompilerError(trimmed_message) from None
        torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
        error: failed to legalize operation 'torch.aten.t' that was explicitly marked illegal
        note: see current operation: %487 = "torch.aten.t"(%486) : (!torch.tensor) -> !torch.tensor

For Torch-MLIR developers, the error can be reproduced with:
        $ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints,torch.aten.slice_scatter})' /tmp/_lambda.mlir
        Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints,torch.aten.slice_scatter})' /tmp/_lambda.mlir 
 Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.


        The above exception was the direct cause of the following exception:

        Traceback (most recent call last):
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 302, in compile_and_run_test
            trace = config.run(compiled, golden_trace)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/torchdynamo.py", line 70, in run
            output = f(getattr(artifact, item.symbol), *item.inputs)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 194, in _fn
            return fn(*args, **kwargs)
          File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/torchdynamo.py", line 54, in f
            return method(*inputs)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 308, in catch_errors
            return callback(frame, cache_size)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 476, in _convert_frame
            result = inner_convert(frame, cache_size)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 118, in _fn
            return fn(*args, **kwargs)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 90, in time_wrapper
            r = func(*args, **kwargs)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 349, in _convert_frame_assert
            return _compile(
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _compile
            out_code = transform_code_object(code, transform)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
            transformations(instructions, code_options)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 392, in transform
            tracer.run()
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1624, in run
            super().run()
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 490, in run
            and self.step()
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 460, in step
            getattr(self, inst.opname)(inst)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1686, in RETURN_VALUE
            self.output.compile_subgraph(self)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 359, in compile_subgraph
            self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 429, in compile_and_call_fx_graph
            compiled_fn = self.call_user_compiler(gm)
          File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 466, in call_user_compiler
            raise BackendCompilerFailed(self.compiler_fn, e) from e
        torch._dynamo.exc.BackendCompilerFailed: wrapper_backend raised TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
        error: failed to legalize operation 'torch.aten.t' that was explicitly marked illegal
        note: see current operation: %487 = "torch.aten.t"(%486) : (!torch.tensor) -> !torch.tensor


        For Torch-MLIR developers, the error can be reproduced with:
        $ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints,torch.aten.slice_scatter})' /tmp/_lambda.mlir
        Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.


        Set torch._dynamo.config.verbose=True for more information
You can suppress this exception and fall back to eager by setting:
            torch._dynamo.config.suppress_errors = True
```
The failure is same for all the 7 tests.

**Comment by powderluv** [comment]
should we try with `torch._dynamo.config.verbose=True`

**Comment by vivekkhandelwal1** [comment]
Closed with https://github.com/llvm/torch-mlir/commit/e7edcc62fde300d026674af64fbb24f3f76caf2a.
