### ISSUE TITLE
TorchMlirCompilerError while using `torch.nn.BatchNorm2d`

### ISSUE THREAD

**Issue by xlindo** [llvm/torch-mlir#1665]
For simplicity, there is the code,

```python3
import torch
import torch_mlir

class BN_TEST(torch.nn.Module):
    def __init__(self):
        super(BN_TEST, self).__init__()
        self.conv = torch.nn.Sequential(
            torch.nn.Conv2d(in_channels=3,
                            out_channels=16,
                            kernel_size=3,
                            stride=1,
                            padding=1,
                            bias=False),
            torch.nn.BatchNorm2d(16),
            torch.nn.ReLU(inplace=True)
        )

    def forward(self, x):

        return self.conv(x)


bn_test = BN_TEST()
module = torch_mlir.compile(bn_test, torch.randn(1, 3, 32, 32), torch_mlir.OutputType.TOSA)

print("TORCH OutputType\n", module.operation.get_asm(large_elements_limit=10))
```

which outputs,

```sh
❯ python3 bn_test.py
Traceback (most recent call last):
  File "/home/shared/shared_prjs/github/mlir-in-action/Torch-MLIR/tiny_IC/model/bn_test/bn_test.py", line 24, in <module>
    module = torch_mlir.compile(bn_test, torch.randn(1, 3, 32, 32), torch_mlir.OutputType.TOSA)
  File "/home/shared/shared_prjs/github/mlir_env_pure_pip/lib/python3.10/site-packages/torch_mlir/__init__.py", line 366, in compile
    run_pipeline_with_repro_report(
  File "/home/shared/shared_prjs/github/mlir_env_pure_pip/lib/python3.10/site-packages/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: module initializers
note: see current operation: "torch.initialize.global_slots"(%10) {slotSymNames = [@conv.1.num_batches_tracked]} : (!torch.tensor<[],si64>) -> ()
note: this is likely due to InlineGlobalSlots being unable to inline a global slot


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints,torch.aten.native_layer_norm,torch.aten.linear})' /tmp/BN_TEST.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

If `torch.nn.BatchNorm2d(16),` is commented, the output is 

```sh
❯ python3 bn_test.py
TORCH OutputType
 module attributes {torch.debug_module_name = "BN_TEST"} {
  func.func @forward(%arg0: tensor<1x3x32x32xf32>) -> tensor<1x16x32x32xf32> {
    %0 = "tosa.const"() {value = dense_resource<__elided__> : tensor<16x3x3x3xf32>} : () -> tensor<16x3x3x3xf32>
    %1 = "tosa.const"() {value = dense<0.000000e+00> : tensor<16xf32>} : () -> tensor<16xf32>
    %2 = "tosa.const"() {value = dense<[0, 2, 3, 1]> : tensor<4xi32>} : () -> tensor<4xi32>
    %3 = "tosa.const"() {value = dense<[0, 3, 1, 2]> : tensor<4xi32>} : () -> tensor<4xi32>
    %4 = "tosa.transpose"(%arg0, %2) : (tensor<1x3x32x32xf32>, tensor<4xi32>) -> tensor<1x32x32x3xf32>
    %5 = "tosa.transpose"(%0, %2) : (tensor<16x3x3x3xf32>, tensor<4xi32>) -> tensor<16x3x3x3xf32>
    %6 = "tosa.conv2d"(%4, %5, %1) {dilation = [1, 1], pad = [1, 1, 1, 1], stride = [1, 1]} : (tensor<1x32x32x3xf32>, tensor<16x3x3x3xf32>, tensor<16xf32>) -> tensor<1x32x32x16xf32>
    %7 = "tosa.transpose"(%6, %3) : (tensor<1x32x32x16xf32>, tensor<4xi32>) -> tensor<1x16x32x32xf32>
    %8 = "tosa.clamp"(%7) {max_fp = 3.40282347E+38 : f32, max_int = 2147483647 : i64, min_fp = 0.000000e+00 : f32, min_int = 0 : i64} : (tensor<1x16x32x32xf32>) -> tensor<1x16x32x32xf32>
    return %8 : tensor<1x16x32x32xf32>
  }
}
```

### Environment

Ubuntu 22.04, Python 3.10 and 

```sh
torch              1.14.0.dev20221122+cpu
torch-mlir         20221129.672
```

**Comment by ramiro050** [comment]
Hi @xlindo, the issue is that `torch.nn.BatchNorm2d` is modifying the state of the module, which is currently unsupported (see thread: https://github.com/llvm/torch-mlir/issues/683). If we look at the IR generated after some passes have taken place:

```mlir
// -----// IR Dump After InlineGlobalSlots (torch-inline-global-slots) //----- //
module attributes {torch.debug_module_name = "BN_TEST"} {
  torch.global_slot.module_initializer {
    %int1 = torch.constant.int 1
    %false = torch.constant.bool false
    %none = torch.constant.none
    %true = torch.constant.bool true
    %0 = torch.tensor.literal(dense_resource<__elided__> : tensor<16x3x3x3xf32>) : !torch.tensor<[16,3,3,3],f32>
    %1 = torch.prim.ListConstruct %int1, %int1, %int1, %int1 : (!torch.int, !torch.int, !torch.int, !torch.int) -> !torch.list<int>
    %2 = torch.tensor.literal(dense<1.000000e+00> : tensor<16xf32>) : !torch.tensor<[16],f32>
    %3 = torch.tensor.literal(dense<0.000000e+00> : tensor<16xf32>) : !torch.tensor<[16],f32>
    %4 = torch.tensor.literal(dense<0.000000e+00> : tensor<16xf32>) : !torch.tensor<[16],f32>
    %5 = torch.tensor.literal(dense<1.000000e+00> : tensor<16xf32>) : !torch.tensor<[16],f32>
    %6 = torch.tensor.literal(dense<0> : tensor<si64>) : !torch.tensor<[],si64>
    torch.initialize.global_slots [
      @conv.1.num_batches_tracked(%6 : !torch.tensor<[],si64>)
    ]
  }
  torch.global_slot "private" @conv.1.num_batches_tracked : !torch.tensor
  func.func @forward(%arg0: !torch.vtensor<[1,3,32,32],f32>) -> !torch.vtensor<[1,16,32,32],f32> {
    %false = torch.constant.bool false
    %int1 = torch.constant.int 1
    %0 = torch.vtensor.literal(dense<1.000000e+00> : tensor<16xf32>) : !torch.vtensor<[16],f32>
    %1 = torch.vtensor.literal(dense<0.000000e+00> : tensor<16xf32>) : !torch.vtensor<[16],f32>
    %2 = torch.vtensor.literal(dense_resource<__elided__> : tensor<16x3x3x3xf32>) : !torch.vtensor<[16,3,3,3],f32>
    %none = torch.constant.none
    %float1.000000e-05 = torch.constant.float 1.000000e-05
    %true = torch.constant.bool true
    %float1.000000e-01 = torch.constant.float 1.000000e-01
    %3 = torch.prim.ListConstruct %int1, %int1 : (!torch.int, !torch.int) -> !torch.list<int>
    %4 = torch.prim.ListConstruct  : () -> !torch.list<int>
    %5 = torch.aten.convolution %arg0, %2, %none, %3, %3, %3, %false, %4, %int1 : !torch.vtensor<[1,3,32,32],f32>, !torch.vtensor<[16,3,3,3],f32>, !torch.none, !torch.list<int>, !torch.list<int>, !torch.list<int>, !torch.bool, !torch.list<int>, !torch.int -> !torch.vtensor<[1,16,32,32],f32>
    %6 = torch.global_slot.get @conv.1.num_batches_tracked : !torch.tensor
    %7 = torch.copy.to_vtensor %6 : !torch.vtensor
    %8 = torch.aten.add.Scalar %7, %int1, %int1 : !torch.vtensor, !torch.int, !torch.int -> !torch.vtensor
    torch.overwrite.tensor.contents %8 overwrites %6 : !torch.vtensor, !torch.tensor
    %9 = torch.aten.batch_norm %5, %0, %1, %1, %0, %true, %float1.000000e-01, %float1.000000e-05, %true : !torch.vtensor<[1,16,32,32],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.vtensor<[16],f32>, !torch.bool, !torch.float, !torch.float, !torch.bool -> !torch.vtensor<[1,16,32,32],f32>
    %10 = torch.aten.relu %9 : !torch.vtensor<[1,16,32,32],f32> -> !torch.vtensor<[1,16,32,32],f32>
    return %10 : !torch.vtensor<[1,16,32,32],f32>
  }
}
```

we see that what seems to be a simple counter variable `conv.1.num_batches_tracked`

```mlir
    %6 = torch.global_slot.get @conv.1.num_batches_tracked : !torch.tensor
```

is not being inlined because the tensor is mutated later on in the graph by `torch.overwrite.tensor.contents`. This leads to your error, since `torch.global_slot.get` is expected to get inlined at some point in the lowering.

**Comment by xlindo** [comment]
Thanks for your explanation, @ramiro050

**Comment by chenghuaWang** [comment]
@ramiro050 Hi, Is torch-mlir supoorted `torch.nn.BatchNorm2d()` now ? I want to use torch-mlir for my own inference framework, and `torch.nn.BatchNorm2d()` is a quite common operator. 

Another question I would like to ask is：
Why do some mlir-based compilers inline the parameters of the network into IR? For torch-mlir:
```python
class net(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.conv = torch.nn.Conv2d(3, 16, 3, 1, 1)

  def forward(self, x):
    return self.conv(x)

mlir = torch_mlir.compile(
    net(),
    torch.ones([1, 3, 192, 192]),
    output_type="LINALG_ON_TENSORS",
    use_tracing=False)
```
the output is:
![image](https://github.com/llvm/torch-mlir/assets/68260701/3da36528-5563-42a5-9e54-d5bdd5113916)

`%cst` and `%cst_0` is the parameters of  `torch.nn.Conv2d(3, 16, 3, 1, 1)`. Why don't they place the parameters separately and use a global id to index them? For example:

```
'net.conv_1.bias': [...],
'net.conv_1.kernel': [...],
```
If we use this method. In IR, a unique placeholder symbol is used to indicate where in the index table the parameter is located. When these parameters are needed, the framework that interprets mlir or the compiled program can be dispatched with these parameters in advance, not at time of running. And this also facilitates the updating of new model parameters.

I'm just starting out mlir, these questions may sound silly😢 .
