### ISSUE TITLE
LSTMCell issue

### ISSUE THREAD

**Issue by hanchenye** [llvm/torch-mlir#1675]
Hi,

I'm trying a trivial model with LSTMCell:

```python
class Foo(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.cell = nn.LSTMCell(65, 512)

    def forward(self, h0, c0, k0):
        h1, _ = self.cell(k0, (h0, c0))
        return h1


module = torch_mlir.compile(
    Foo(),
    (torch.randn(2, 512), torch.randn(2, 512), torch.randn(2, 65)),
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=True)
print(module)
```

The compiler failed with the following traces:
```
Traceback (most recent call last):
  File "/home/hanchenye/workspace/foo.py", line 38, in <module>
    module = torch_mlir.compile(
  File "/home/hanchenye/.local/lib/python3.10/site-packages/torch_mlir/__init__.py", line 347, in compile
    run_pipeline_with_repro_report(
  File "/home/hanchenye/.local/lib/python3.10/site-packages/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: non-value tensor type
note: see current operation: %11 = "torch.copy.to_tensor"(%10) : (!torch.vtensor<[2,2048],f32>) -> !torch.tensor<[2,2048],f32>
note: this is likely due to a missing case in the MaximizeValueSemantics pass
```

I'm using the most recent pre-built package:
```
mpmath-1.2.1 networkx-3.0rc1 sympy-1.11.1 torch-1.14.0.dev20221204+cpu torch-mlir-0.0.0 torchvision-0.15.0.dev20221204+cpu
```

Thanks in advance!

**Comment by makslevental** [comment]
@hanchenye 

```python
class Foo(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.cell = nn.LSTMCell(65, 512)

    def forward(self, h0, c0, k0):
        h1, _ = self.cell(k0, (h0, c0))
        return h1

foo = Foo()
foo.eval()
t = torch.jit.script(foo)
f = torch.jit.freeze(t)
print(f.graph)
```

you'll see 

```
graph(%self : __torch__.___torch_mangle_0.Foo,
      %h0.1 : Tensor,
      %c0.1 : Tensor,
      %k0.1 : Tensor):
  ...
  %50 : Tensor, %51 : Tensor = aten::lstm_cell(%input, %49, %self.cell.weight_ih, %self.cell.weight_hh, %self.cell.bias_ih, %self.cell.bias_hh) 
  ...
  return (%h1.1)
```

which hasn't been [lowered yet](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L242). @vivekkhandelwal1 is `aten::lstm_cell` somewhere on the list of prioritized ops?

**Comment by vivekkhandelwal1** [comment]
Hi @makslevental, I don't think this is on our list of ops to be added.

**Comment by hanchenye** [comment]
> Hi @makslevental, I don't think this is on our list of ops to be added.

Hi @vivekkhandelwal1, I see. Then would it possible to provide some guidance on how to add the support? I'd be more than happy to file a PR to support this.

**Comment by makslevental** [comment]
@hanchenye I don't remember if there are dev docs on this (there might be?) but this PR shows the right set of files to touch https://github.com/llvm/torch-mlir/pull/1581. The hard, usually, part is getting a conformant implementation/lowering (since it should conform to PyTorch's).

**Comment by hanchenye** [comment]
@makslevental Thanks a lot! Will look into it soon.

**Comment by hanchenye** [comment]
Just a quick update:
1. I tried to add an LstmCell operation in MLIR and succeeded, but the importer always generates a separate function `LSTMCell.forward` instead of keeping the original aten lstm_cell operator: https://github.com/llvm/torch-mlir/blob/163d19cce6ba1d97269f948438da206e38f53f6e/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp#L183 Please correct me if I've missed anything. I didn't dig more but I believe there should be a way to work around this?
2. Only one operator in `LSTMCell.forward` is not supported - unsafe_chunk. I tried to add this operation in MLIR but failed, torch_ods_gen cannot recognize this operation: `KeyError: 'aten::unsafe_chunk : (Tensor, int, int?) -> (Tensor[])'`.

I will use a customized LSTMCell implementation instead of nn.LSTMCell for now.

**Comment by Groverkss** [comment]
This can now also be lowered by using torch.fx decompositions: https://github.com/pytorch/pytorch/pull/91124
