### ISSUE TITLE
Issue with the `Aten_IndexPutImpl` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1682]
Hi, while lowering a model, I'm getting an IR sequence with the `aten._index_put_impl` op, as follows:
```
%16289 = torch.prim.ListConstruct %16283 : (!torch.vtensor<[1,77],si64>) -> !torch.list<vtensor> loc(#loc11250)
%16290 = torch.aten._index_put_impl %16288, %16289, %16286, %true, %false : !torch.vtensor<[49409,768],f32>, !torch.list<vtensor>, !torch.vtensor<[1,77,768],f32>, !torch.bool, !torch.bool -> !torch.vtensor<[49409,768],f32> loc(#loc11250)
```
While I try to run this op on PyTorch with the same shape, I'm getting a runtime error:
```
>>> torch.ops.aten._index_put_impl(torch.randn(49409, 768), (torch.randint(10, (1, 77))), torch.randn(1, 77, 768), accumulate=True, unsafe=False).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_ops.py", line 500, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: shape mismatch: value tensor of shape [1, 77, 768] cannot be broadcast to indexing result of shape [77, 768]
```
On the other hand, if we add the following e2e test in Torch-MLIR:
```
class IndexPutImplTestModule(torch.nn.Module):

    def __init__(self):
        super().__init__()

    @export
    @annotate_args([
        None,
        ([49409, 768], torch.float32, True),
        ([1, 77], torch.int64, True),
        ([1, 77, 768], torch.float32, True),
    ])
    def forward(self, input, index, value):
        return torch.ops.aten._index_put_impl_(input, (index, ),
                                               value,
                                               accumulate=True,
                                               unsafe=False)


@register_test_case(
    module_factory=lambda: IndexPutImplTestModule())
def IndexPutImplTestModule_basic(module, tu: TestUtils):
    module.forward(tu.rand(49409, 768), tu.randint(1, 77, high=10), tu.rand(1, 77, 768))
```
And run the above test it generates the Torch-IR but fails during the lowering, with the following error:
```
  * Pattern : 'torch.aten._index_put_impl -> ()' {
Trying to match "(anonymous namespace)::ConvertAten_IndexPutImplOp"
    ** Failure : unimplemented: index tensor with rank != 1 is not supported
"(anonymous namespace)::ConvertAten_IndexPutImplOp" result 0
  } -> FAILURE: pattern failed to match
} -> FAILURE: no matched legalization pattern
```
My question is if the same op does not run in PyTorch and throws a runtime error then how is it running in Torch-MLIR, also shouldn't this throw a runtime error as well, if it is invalid?
@silvasean @ramiro050

**Comment by ramiro050** [comment]
The PyTorch error is due to a typo in the arguments. The second argument should be a list or a tuple of tensors (a tuple of a single element should have a comma after the first parenthesis). If you pass a tuple of list, there is no error:

```python
torch.ops.aten._index_put_impl(torch.randn(49409, 768), (torch.randint(10, (1, 77))), torch.randn(1, 77, 768), accumulate=True, unsafe=False).shape
```

So the op generated is valid.

**Comment by ramiro050** [comment]
@vivekkhandelwal1, has this issue been resolved?

**Comment by vivekkhandelwal1** [comment]
> @vivekkhandelwal1, has this issue been resolved?

Hi @ramiro050, I have a patch for this locally. I will close this once it is upstreamed.

**Comment by vivekkhandelwal1** [comment]
I'm closing this issue, since this PR is merged: https://github.com/llvm/torch-mlir/pull/1762
