### ISSUE TITLE
Error when trying to compile torch.linalg triangular solver

### ISSUE THREAD

**Issue by atgutier** [llvm/torch-mlir#1738]
```python
import torch
import torch_mlir

class spts(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a, b):
        return torch.linalg.solve_triangular(a, b, upper=False)

A = torch.randn(3, 3).tril_()
b = torch.randn(3, 1)
X_ref = torch.linalg.solve_triangular(A, b, upper=False)

print(A)
print(b)
print(X_ref)

program = spts()
mlir = torch_mlir.compile(program, (A, b), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)
```

I am trying to run a triangular solver through the Torch MLIR compiler, however I am getting the below error. I am using Python 3.8.10, Torch 1.14.0.dev20221107+cpu, and Torch MLIR built from change 805d728194f25f886d39bf6d290f773d69b2f6f4. The minimal example above generates:

Traceback (most recent call last):
  File "./spts.py", line 22, in <module>
    mlir = torch_mlir.compile(program, (A, b), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)
  File "~/torch_mlir/torch_mlir/__init__.py", line 274, in compile
    run_pipeline_with_repro_report(
  File "~/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: tensor with unknown rank
note: see current operation: %2 = "torch.tensor_static_info_cast"(%arg0) : (!torch.vtensor<[3,3],f32>) -> !torch.vtensor<*,f32>
note: this is likely due to a missing shape transfer function in shape_lib_gen.py

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints}' /tmp/spts.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

**Comment by ramiro050** [comment]
Hi @atgutier, the error you're getting is due to the fact that there is currently no support in torch-mlir for the `aten.linalg_solve_triangular` op. This can be seen from running the reproducer in the error message with the flag `-mlir-print-ir-after-all`. This will dump IR where the op `aten.linalg_solve_triangular` is inside a `torch.operator`, signifying that torch-mlir does not know how to handle that op.

```mlir
  %4 = torch.operator "aten.linalg_solve_triangular"(%1, %3, %false, %true, %false) : (!torch.tensor<*,f32>, !torch.tensor<*,f32>, !torch.bool, !torch.bool, !torch.bool) -> !torch.tensor
```
