### ISSUE TITLE
tanh + select.int causing compiler core dumped

### ISSUE THREAD

**Issue by li-plus** [llvm/torch-mlir#1748]
In this PR #1594, `AtenTanhOp` has been removed from this type refinement list:

https://github.com/llvm/torch-mlir/blob/52669cbbd5973d537a7d23720822a3b45dd07495/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L675-L689

This is causing some subtle problems. For example, now we cannot compile the below simple model.

```python
import torch
import torch.nn as nn
import torch_mlir

class Model(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return torch.tanh(x + 1)[0]

model = Model().eval()
inputs = torch.randn(2, 3)
model = torch.jit.trace(model, inputs)
model.save('model.jit')

model = torch.jit.load('model.jit')
print(model(inputs))
module = torch_mlir.compile(model, inputs, output_type="torch")
print(module)
```

The error log:

```
(thmlir) ➜  ~/ada_local/torch-mlir git:(main) ✗ python3 examples/tanh.py
tensor([0.7073, 0.2370, 0.9675])
python3: /data00/home/lijiahao.plus/ada_local/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h:77: mlir::Type mlir::torch::Torch::BaseTensorType::getDtype() const: Assertion `hasDtype() && "must have a dtype"' failed.
[1]    2719954 abort (core dumped)  python3 examples/tanh.py
```

Backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f03a2b85535 in __GI_abort () at abort.c:79
#2  0x00007f03a2b8540f in __assert_fail_base (fmt=0x7f03a2ce7ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7f028ba9efd3 "hasDtype() && \"must have a dtype\"", 
    file=0x7f028ba9eee9 "/data00/home/lijiahao.plus/ada_local/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h", line=77, 
    function=<optimized out>) at assert.c:92
#3  0x00007f03a2b93102 in __GI___assert_fail (assertion=0x7f028ba9efd3 "hasDtype() && \"must have a dtype\"", 
    file=0x7f028ba9eee9 "/data00/home/lijiahao.plus/ada_local/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h", line=77, 
    function=0x7f028ba9eff5 "mlir::Type mlir::torch::Torch::BaseTensorType::getDtype() const") at assert.c:101
#4  0x00007f0286bd8b5b in mlir::torch::Torch::BaseTensorType::getDtype (this=0x7fff722c4d30)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/include/torch-mlir/Dialect/Torch/IR/TorchTypes.h:77
#5  0x00007f0286e72da2 in computeReductionType (rewriter=..., op=0x7419b30, tensorType=..., dim=..., keepDim=true)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp:74
#6  0x00007f0286e8cbe5 in (anonymous namespace)::DecomposeAtenSelectIntOp::matchAndRewrite (this=0x769fee0, op=..., rewriter=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp:267
#7  0x00007f0286ef0d16 in mlir::detail::OpOrInterfaceRewritePatternBase<mlir::torch::Torch::AtenSelectIntOp>::matchAndRewrite (this=0x769fee0, 
    op=0x7419b30, rewriter=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/llvm/../mlir/include/mlir/IR/PatternMatch.h:329
#8  0x00007f028a4a688b in mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (this=0x7fff722c5770, 
    op=0x7419b30, rewriter=..., canApply=..., onFailure=..., onSuccess=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Rewrite/PatternApplicator.cpp:200
#9  0x00007f028a483c80 in (anonymous namespace)::GreedyPatternRewriteDriver::simplify (this=0x7fff722c5748, regions=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:274
#10 0x00007f028a48322a in mlir::applyPatternsAndFoldGreedily (regions=..., patterns=..., config=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp:417
#11 0x00007f028324d382 in mlir::applyPatternsAndFoldGreedily (op=0x7494d70, patterns=..., config=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h:71
#12 0x00007f0286e67b46 in (anonymous namespace)::DecomposeComplexOpsPass::runOnOperation (this=0x75b8e40)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp:3618
#13 0x00007f02832b44f9 in mlir::detail::OpToOpPassAdaptor::run (pass=0x75b8e40, op=0x7494d70, am=..., verifyPasses=true, parentInitGeneration=1)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:465
#14 0x00007f02832b4b34 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0x7494d70, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0x0, parentInfo=0x7fff722c6150) at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:529
#15 0x00007f02832ba3c3 in mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const (this=0x7fff722c60e8, opInfo=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:749
#16 0x00007f02832b9fc0 in mlir::failableParallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&>(mlir::MLIRContext*, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&)
    (context=0x729b2d0, begin={passManagerIdx = 0, op = 0x7494d70, am = {impl = 0x7831870}}, end=
    {passManagerIdx = 49, op = 0xe, am = {impl = 0x760c080}}, func=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/include/mlir/IR/Threading.h:46
#17 0x00007f02832b5ea6 in mlir::failableParallelForEach<std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> >&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&>(mlir::MLIRContext*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> >&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&) (context=0x729b2d0, 
    range=std::vector of length 1, capacity 1 = {...}, func=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/include/mlir/IR/Threading.h:92
#18 0x00007f02832b5700 in mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl (this=0x74b7230, verifyPasses=true)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:759
#19 0x00007f02832b47bd in mlir::detail::OpToOpPassAdaptor::runOnOperation (this=0x74b7230, verifyPasses=true)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:650
#20 0x00007f02832b44e7 in mlir::detail::OpToOpPassAdaptor::run (pass=0x74b7230, op=0x7376b20, am=..., verifyPasses=true, parentInitGeneration=1)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:463
#21 0x00007f02832b4b34 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0x7376b20, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0x0, parentInfo=0x7fff722c6e80) at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:529
#22 0x00007f02832b8fc3 in mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_6::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0x7fff722c6e50, pipeline=..., root=0x7376b20)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:451
#23 0x00007f02832b8d15 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_6>(long, mlir::OpPassManager&, mlir::Operation*) (
    callable=140735108902480, params=0x7376b20, params=0x7376b20)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#24 0x00007f0284b8f981 in llvm::function_ref<mlir::LogicalResult (mlir::OpPassManager&, mlir::Operation*)>::operator()(mlir::OpPassManager&, mlir::Operation*) const (this=0x74921f0, params=0x7376b20, params=0x7376b20)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#25 0x00007f0284b8f788 in mlir::Pass::runPipeline (this=0x7492180, pipeline=..., op=0x7376b20)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/include/mlir/Pass/Pass.h:195
#26 0x00007f0286f52764 in (anonymous namespace)::LowerToBackendContractPass::runOnOperation (this=0x7492180)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp:277
#27 0x00007f02832b44f9 in mlir::detail::OpToOpPassAdaptor::run (pass=0x7492180, op=0x7376b20, am=..., verifyPasses=true, parentInitGeneration=1)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:465
#28 0x00007f02832b4b34 in mlir::detail::OpToOpPassAdaptor::runPipeline (pm=..., op=0x7376b20, am=..., verifyPasses=true, parentInitGeneration=1, 
    instrumentor=0x0, parentInfo=0x0) at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:529
#29 0x00007f02832b65bf in mlir::PassManager::runPasses (this=0x747ae00, op=0x7376b20, am=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:834
#30 0x00007f02832b64e1 in mlir::PassManager::run (this=0x747ae00, op=0x7376b20)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Pass/Pass.cpp:814
#31 0x00007f02831454d2 in mlirPassManagerRun (passManager=..., module=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/CAPI/IR/Pass.cpp:43
#32 0x00007f028fbab81e in mlir::python::populatePassManagerSubmodule(pybind11::module_&)::$_5::operator()((anonymous namespace)::PyPassManager&, mlir::python::PyModule&) const (this=0x6fd2a48, passManager=..., module=...)
    at /data00/home/lijiahao.plus/ada_local/torch-mlir/externals/llvm-project/mlir/lib/Bindings/Python/Pass.cpp:121
#33 0x00007f028fbab7bf in pybind11::detail::argument_loader<(anonymous namespace)::PyPassManager&, mlir::python::PyModule&>::call_impl<void, mlir::python::populatePassManagerSubmodule(pybind11::module_&)::$_5&, 0ul, 1ul, pybind11::detail::void_type>(mlir::python::populatePassManagerSubmodule(pybind11::module_&)::$_5&, std::integer_sequence<unsigned long, 0ul, 1ul>, pybind11::detail::void_type&&) && (this=0x7fff722c76a8, f=...)
    at /data00/home/lijiahao.plus/miniconda3/envs/thmlir/lib/python3.7/site-packages/pybind11/include/pybind11/cast.h:1439
#34 0x00007f028fbab546 in pybind11::detail::argument_loader<(anonymous namespace)::PyPassManager&, mlir::python::PyModule&>::call<void, pybind11::detail::void_type, mlir::python::populatePassManagerSubmodule(pybind11::module_&)::$_5&> (this=0x7fff722c76a8, f=...)
    at /data00/home/lijiahao.plus/miniconda3/envs/thmlir/lib/python3.7/site-packages/pybind11/include/pybind11/cast.h:1413
...
```

**Comment by li-plus** [comment]
Already fixed. Closing this issue.
