### ISSUE TITLE
Error: unhandled prim::Constant node: %123 : () = prim::Constant[value=()]()

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1824]
Hi, I'm trying to generate a backwards graph using Torchdynamo backend in Torch-MLIR. But I'm getting the following error:
```
Traceback (most recent call last):
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 674, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1047, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/optimizations/training.py", line 78, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2453, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 96, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2150, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1412, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1062, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dynamo.py", line 130, in wrapper_backend
    user_callable = user_backend(gm, example_inputs)
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 532, in refbackend_torchdynamo_backend
    mlir_module = torch_mlir.compile(
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 358, in compile
    raise Exception(f"""
Exception: 
PyTorch TorchScript module -> torch-mlir Object Graph IR import failed with:
### Importer C++ Exception:
see diagnostics
### Importer Diagnostics:
error: unhandled prim::Constant node: %123 : () = prim::Constant[value=()]()




The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 757, in <module>
    training_function(text_encoder, vae, unet)
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 737, in training_function
    predictions(train_func, lambda x, y, z: dynamo_callable(torch.from_numpy(x), torch.from_numpy(y), torch.from_numpy(z)).detach().numpy(), batch["input_ids"], batch["pixel_values"], params[0].detach())
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 629, in predictions
    prediction = torch.from_numpy(jit_func(batchA.numpy(), batchB.numpy(), params.numpy()))
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 737, in <lambda>
    predictions(train_func, lambda x, y, z: dynamo_callable(torch.from_numpy(x), torch.from_numpy(y), torch.from_numpy(z)).detach().numpy(), batch["input_ids"], batch["pixel_values"], params[0].detach())
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 577, in train_func
    latents = vae.encode(batch_pixel_values).latent_dist.sample().detach()
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 594, in <graph break in train_func>
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 609, in <graph break in train_func>
    loss.backward()
  File "/home/vivek/work/02_07/vivekkhandelwal1-torch-mlir/scripts_python/torchdynamo_sd_avinash.py", line 620, in <graph break in train_func>
    optimizer.step()
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 32, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/optim/adamw.py", line 113, in step
    self._cuda_graph_capture_health_check()
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/optim/adamw.py", line 132, in <graph break in step>
    adamw(
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 480, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 96, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 339, in _convert_frame_assert
    return _compile(
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 400, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 387, in transform
    tracer.run()
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1684, in run
    super().run()
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 538, in run
    and self.step()
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 501, in step
    getattr(self, inst.opname)(inst)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1750, in RETURN_VALUE
    self.output.compile_subgraph(self)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 551, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 598, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 679, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compiler_fn raised Exception: 
PyTorch TorchScript module -> torch-mlir Object Graph IR import failed with:
### Importer C++ Exception:
see diagnostics
### Importer Diagnostics:
error: unhandled prim::Constant node: %123 : () = prim::Constant[value=()]()

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

@silvasean @ramiro050 Do you have any idea about this error?

**Comment by silvasean** [comment]
What was the solution? In general when closing an issue it is a good idea to comment on why the problem is no longer important.

**Comment by vivekkhandelwal1** [comment]
I got this issue fixed by applying the below transformation on the fx graph:
```
def _returns_nothing(fx_g: torch.fx.GraphModule) -> bool:
    for node in fx_g.graph.nodes:
        if node.op == "output":
            assert len(node.args) == 1, "Output node must have a single argument"
            node_arg = node.args[0]
            if isinstance(node_arg, tuple):
                return len(node_arg) == 0
    return False
```
