### ISSUE TITLE
test case error 

### ISSUE THREAD

**Issue by wm901115nwpu** [llvm/torch-mlir#1833]
I use newest main bratch, I get error as follows:
[52/59] Running the torch-mlir Python regression tests
FAIL: TORCH_MLIR_PYTHON :: debug/lockstep_basic.py (1 of 16)
******************** TEST 'TORCH_MLIR_PYTHON :: debug/lockstep_basic.py' FAILED ********************
Script:
--
: 'RUN: at line 6';   /Users/unicorn/miniconda3/envs/torch-mlir/bin/python3.9 /Users/unicorn/workspace/torch-mlir/python/test/debug/lockstep_basic.py | /Users/unicorn/workspace/torch-mlir/build/bin/FileCheck /Users/unicorn/workspace/torch-mlir/python/test/debug/lockstep_basic.py
--
Exit Code: 2

Command Output (stderr):
--
Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file CommandLine.h, line 864.
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /Users/unicorn/workspace/torch-mlir/build/bin/FileCheck /Users/unicorn/workspace/torch-mlir/python/test/debug/lockstep_basic.py

--

********************
********************
Failed Tests (1):
  TORCH_MLIR_PYTHON :: debug/lockstep_basic.py

Testing Time: 7.17s
  Passed: 15
  Failed:  1
FAILED: tools/torch-mlir/python/test/CMakeFiles/check-torch-mlir-python /Users/unicorn/workspace/torch-mlir/build/tools/torch-mlir/python/test/CMakeFiles/check-torch-mlir-python
cd /Users/unicorn/workspace/torch-mlir/build/tools/torch-mlir/python/test && /Users/unicorn/miniconda3/envs/torch-mlir/bin/python3.9 /Users/unicorn/workspace/torch-mlir/build/./bin/llvm-lit -sv /Users/unicorn/workspace/torch-mlir/build/tools/torch-mlir/python/test
ninja: build stopped: subcommand failed.

**Comment by ramiro050** [comment]
Are you able to run the `lockstep_basic.py` file without getting errors?

**Comment by wm901115nwpu** [comment]
I can't run it only, because I use torch-mlir/build_tools/build_standalone.sh installed.

**Comment by wm901115nwpu** [comment]
Traceback (most recent call last):
  File "/Users/unicorn/workspace/torch-mlir/python/test/debug/lockstep_basic.py", line 12, in <module>
    from torch_mlir.dynamo import make_simple_dynamo_backend
  File "/Users/unicorn/workspace/torch-mlir/python/torch_mlir/__init__.py", line 15, in <module>
    from torch_mlir.passmanager import PassManager
ModuleNotFoundError: No module named 'torch_mlir.passmanager'
FileCheck error: '<stdin>' is empty.

**Comment by wm901115nwpu** [comment]
Traceback (most recent call last):
  File "/Users/unicorn/workspace/torch-mlir/python/test/debug/lockstep_basic.py", line 12, in <module>
    from torch_mlir.dynamo import make_simple_dynamo_backend
  File "/Users/unicorn/workspace/torch-mlir/python/torch_mlir/__init__.py", line 15, in <module>
    from torch_mlir.passmanager import PassManager
ModuleNotFoundError: No module named 'torch_mlir.passmanager'
FileCheck error: '<stdin>' is empty.

**Comment by wm901115nwpu** [comment]
python python/test/debug/lockstep_basic.py                                                                                                                                  ─╯
Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file CommandLine.h, line 864.
[2]    4080 abort      python python/test/debug/lockstep_basic.py

**Comment by ramiro050** [comment]
Can you get a backtrace of the assertion? You should be able to do `gdb --args python python/test/debug/lockstep_basic.py`, then use the `r` command to run, then `bt` command to get backtrace

**Comment by wm901115nwpu** [comment]
─ gdb --args python python/test/debug/lockstep_basic.py                                                                                                                       ─╯
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin22.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...

warning: `/tmp/lto.o': can't open to read symbols: No such file or directory.
(No debugging symbols found in python)

I find that MACOS gdb have something wrong.
