### ISSUE TITLE
[torchdynamo] `UpSampleNearest2dDynamicFactor_basic` fails after PyTorch update

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1858]
The test `UpSampleNearest2dDynamicFactor_basic` is failing with the following error for TorchDynamo after some changes here:https://github.com/pytorch/pytorch/commit/8ecda19607a819d0387341b6c2d31d29e05a33ab.
Error:
```
FAIL - "UpSampleNearest2dDynamicFactor_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "UpSampleNearest2dDynamicFactor_basic"
        @ trace item #0 - call to "forward"
        @ output of call to "forward"
        ERROR: value (Tensor with shape=[2, 3, 6, 10], dtype=torch.float32, min=-1.336e-32, max=+0.9152, mean=+0.4837) is not close to golden value (Tensor with shape=[2, 3, 6, 10], dtype=torch.float32, min=+0.02233, max=+0.9152, mean=+0.4777)
```
Right now, I have added this to the xfail set here: https://github.com/llvm/torch-mlir/pull/1857.

**Comment by vivekkhandelwal1** [comment]
I tried debugging the issue, but found out that the difference in IR's generated before and after the changes are made in decomposition has 2 things different, one is the absence of `floor` op, and second the difference in constant values.

IR before decomp changes:
```
module attributes {torch.debug_module_name = "_lambda"} {
  func.func @forward(%arg0: !torch.vtensor<[2,3,2,2],f32>) -> !torch.vtensor<[2,3,6,10],f32> {
    %int0 = torch.constant.int 0
    %int10 = torch.constant.int 10
    %int4 = torch.constant.int 4
    %false = torch.constant.bool false
    %none = torch.constant.none
    %int1 = torch.constant.int 1
    %int6 = torch.constant.int 6
    %int-1 = torch.constant.int -1
    %float3.333330e-01 = torch.constant.float 0.33333333333333331
    %float2.000000e-01 = torch.constant.float 2.000000e-01
    %cpu = torch.constant.device "cpu"
    %0 = torch.aten.arange.start_step %int0, %int6, %int1, %int6, %none, %cpu, %false : !torch.int, !torch.int, !torch.int, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[6],f32>
    %1 = torch.aten.mul.Scalar %0, %float3.333330e-01 : !torch.vtensor<[6],f32>, !torch.float -> !torch.vtensor<[6],f32>
    %2 = torch.aten.floor %1 : !torch.vtensor<[6],f32> -> !torch.vtensor<[6],f32>
    %3 = torch.prim.NumToTensor.Scalar %int0 : !torch.int -> !torch.vtensor<[],si64>
    %4 = torch.prim.ListConstruct %int6 : (!torch.int) -> !torch.list<int>
    %5 = torch.aten.broadcast_to %3, %4 : !torch.vtensor<[],si64>, !torch.list<int> -> !torch.vtensor<[6],si64>
    %6 = torch.aten.to.dtype %2, %int4, %false, %false, %none : !torch.vtensor<[6],f32>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[6],si64>
    %7 = torch.prim.ListConstruct %int6 : (!torch.int) -> !torch.list<int>
    %8 = torch.aten.broadcast_to %6, %7 : !torch.vtensor<[6],si64>, !torch.list<int> -> !torch.vtensor<[6],si64>
    %9 = torch.aten.unsqueeze %8, %int-1 : !torch.vtensor<[6],si64>, !torch.int -> !torch.vtensor<[6,1],si64>
    %10 = torch.aten.arange.start_step %int0, %int10, %int1, %int6, %none, %cpu, %false : !torch.int, !torch.int, !torch.int, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[10],f32>
    %11 = torch.aten.mul.Scalar %10, %float2.000000e-01 : !torch.vtensor<[10],f32>, !torch.float -> !torch.vtensor<[10],f32>
    %12 = torch.aten.floor %11 : !torch.vtensor<[10],f32> -> !torch.vtensor<[10],f32>
    %13 = torch.prim.NumToTensor.Scalar %int0 : !torch.int -> !torch.vtensor<[],si64>
    %14 = torch.prim.ListConstruct %int10 : (!torch.int) -> !torch.list<int>
    %15 = torch.aten.broadcast_to %13, %14 : !torch.vtensor<[],si64>, !torch.list<int> -> !torch.vtensor<[10],si64>
    %16 = torch.aten.to.dtype %12, %int4, %false, %false, %none : !torch.vtensor<[10],f32>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[10],si64>
    %17 = torch.prim.ListConstruct %int10 : (!torch.int) -> !torch.list<int>
    %18 = torch.aten.broadcast_to %16, %17 : !torch.vtensor<[10],si64>, !torch.list<int> -> !torch.vtensor<[10],si64>
    %19 = torch.prim.ListConstruct %none, %none, %9, %18 : (!torch.none, !torch.none, !torch.vtensor<[6,1],si64>, !torch.vtensor<[10],si64>) -> !torch.list<optional<vtensor>>
    %20 = torch.aten.index.Tensor %arg0, %19 : !torch.vtensor<[2,3,2,2],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[2,3,6,10],f32>
    return %20 : !torch.vtensor<[2,3,6,10],f32>
  }
}
```

IR after decomp changes:
```
module attributes {torch.debug_module_name = "_lambda"} {
  func.func @forward(%arg0: !torch.vtensor<[2,3,2,2],f32>) -> !torch.vtensor<[2,3,6,10],f32> {
    %int0 = torch.constant.int 0
    %int10 = torch.constant.int 10
    %int4 = torch.constant.int 4
    %false = torch.constant.bool false
    %none = torch.constant.none
    %int1 = torch.constant.int 1
    %int6 = torch.constant.int 6
    %int-1 = torch.constant.int -1
    %float4.347830e-01 = torch.constant.float 0.43478260869565222
    %float2.127660e-01 = torch.constant.float 0.21276595744680851
    %cpu = torch.constant.device "cpu"
    %0 = torch.aten.arange.start_step %int0, %int6, %int1, %int6, %none, %cpu, %false : !torch.int, !torch.int, !torch.int, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[6],f32>
    %1 = torch.aten.mul.Scalar %0, %float4.347830e-01 : !torch.vtensor<[6],f32>, !torch.float -> !torch.vtensor<[6],f32>
    %2 = torch.prim.NumToTensor.Scalar %int0 : !torch.int -> !torch.vtensor<[],si64>
    %3 = torch.prim.ListConstruct %int6 : (!torch.int) -> !torch.list<int>
    %4 = torch.aten.broadcast_to %2, %3 : !torch.vtensor<[],si64>, !torch.list<int> -> !torch.vtensor<[6],si64>
    %5 = torch.aten.to.dtype %1, %int4, %false, %false, %none : !torch.vtensor<[6],f32>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[6],si64>
    %6 = torch.prim.ListConstruct %int6 : (!torch.int) -> !torch.list<int>
    %7 = torch.aten.broadcast_to %5, %6 : !torch.vtensor<[6],si64>, !torch.list<int> -> !torch.vtensor<[6],si64>
    %8 = torch.aten.unsqueeze %7, %int-1 : !torch.vtensor<[6],si64>, !torch.int -> !torch.vtensor<[6,1],si64>
    %9 = torch.aten.arange.start_step %int0, %int10, %int1, %int6, %none, %cpu, %false : !torch.int, !torch.int, !torch.int, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[10],f32>
    %10 = torch.aten.mul.Scalar %9, %float2.127660e-01 : !torch.vtensor<[10],f32>, !torch.float -> !torch.vtensor<[10],f32>
    %11 = torch.prim.NumToTensor.Scalar %int0 : !torch.int -> !torch.vtensor<[],si64>
    %12 = torch.prim.ListConstruct %int10 : (!torch.int) -> !torch.list<int>
    %13 = torch.aten.broadcast_to %11, %12 : !torch.vtensor<[],si64>, !torch.list<int> -> !torch.vtensor<[10],si64>
    %14 = torch.aten.to.dtype %10, %int4, %false, %false, %none : !torch.vtensor<[10],f32>, !torch.int, !torch.bool, !torch.bool, !torch.none -> !torch.vtensor<[10],si64>
    %15 = torch.prim.ListConstruct %int10 : (!torch.int) -> !torch.list<int>
    %16 = torch.aten.broadcast_to %14, %15 : !torch.vtensor<[10],si64>, !torch.list<int> -> !torch.vtensor<[10],si64>
    %17 = torch.prim.ListConstruct %none, %none, %8, %16 : (!torch.none, !torch.none, !torch.vtensor<[6,1],si64>, !torch.vtensor<[10],si64>) -> !torch.list<optional<vtensor>>
    %18 = torch.aten.index.Tensor %arg0, %17 : !torch.vtensor<[2,3,2,2],f32>, !torch.list<optional<vtensor>> -> !torch.vtensor<[2,3,6,10],f32>
    return %18 : !torch.vtensor<[2,3,6,10],f32>
  }
}
```

**Comment by ramiro050** [comment]
So the updated PyTorch decomposition is wrong now?

**Comment by silvasean** [comment]
@ramiro050 I think it would be a good idea to add a "no-op" dynamo config that just returns `fx_graph` here to verify such failures: https://github.com/llvm/torch-mlir/blob/cc819e73dd5a48162dcfc099bbdf1b54ca6831da/python/torch_mlir_e2e_test/configs/torchdynamo.py#L21

It should then compose pretty nicely: we have the "vanilla dynamo xfails" and then the Torch-MLIR+Dynamo xfails are "VANILLA_XFAILS + { ... }".

**Comment by vivekkhandelwal1** [comment]
The issue is with the decomposition itself. After the changes in this patch particularly at this line: https://github.com/pytorch/pytorch/blob/8ecda19607a819d0387341b6c2d31d29e05a33ab/torch/_decomp/decompositions.py#L2059. The decomposition turns out to be invalid. It gives the following error:
```
Traceback (most recent call last):
  File "/home/vivek/work/misc/vivekkhandelwal1-pytorch/upsample_nearest2d.py", line 58, in <module>
    out_decomp = upsample_nearest2d(
  File "/home/vivek/work/misc/vivekkhandelwal1-pytorch/upsample_nearest2d.py", line 38, in upsample_nearest2d
    result = input[:, :, h_indices, w_indices]
IndexError: index 2 is out of bounds for dimension 0 with size 2
```
You can run the below code inside the PyTorch repo, and reproduce the error:
```
import torch
from typing import Callable, cast, Iterable, List, Optional, Tuple, Union
from torch import sym_float, sym_int, Tensor
import torch._prims_common as utils

def _compute_upsample_nearest_indices(input, output_size, scales):
    # For each dim in output_size, compute the set of input indices used
    # to produce the upsampled output.
    indices = []
    num_spatial_dims = len(output_size)
    for d in range(num_spatial_dims):
        # Math matches aten/src/ATen/native/cpu/UpSampleKernel.cpp
        # Indices are computed as following:
        # scale = isize / osize
        # input_index = floor(output_index * scale)
        # Same as OpenCV INTER_NEAREST
        osize = output_size[d]
        output_indices = torch.arange(osize, dtype=input.dtype, device=input.device)
        isize = input.shape[-num_spatial_dims + d]
        scale = isize / (isize * scales[d]) if scales[d] is not None else isize / osize
        input_indices = (output_indices * scale).to(torch.int64)
        for _ in range(num_spatial_dims - 1 - d):
            input_indices = input_indices.unsqueeze(-1)
        indices.append(input_indices)
    return tuple(indices)

def upsample_nearest2d(
    input: Tensor,
    output_size: List[int],
    scales_h: Optional[float] = None,
    scales_w: Optional[float] = None,
) -> Tensor:
    h_indices, w_indices = _compute_upsample_nearest_indices(
        input, output_size, (scales_h, scales_w)
    )
    result = input[:, :, h_indices, w_indices]

    # convert output to correct memory format, if necessary
    memory_format = utils.suggest_memory_format(input)

    # following "heuristic: only use channels_last path when it's faster than the contiguous path"
    _, n_channels, _, _ = input.shape
    if input.device.type == "cuda" and n_channels < 4:
        memory_format = torch.contiguous_format

    result = result.contiguous(memory_format=memory_format)

    return result

inputVec = torch.rand((2, 3, 2, 2))
out_torch = torch._C._nn.upsample_nearest2d(
    inputVec, output_size=[6, 10], scales_h=2.3, scales_w=4.7
)

out_decomp = upsample_nearest2d(
    inputVec, output_size=[6, 10], scales_h=2.3, scales_w=4.7
)

print(out_torch == out_decomp)
```
Since it is accessing the out-of-bound index, that's why during the run in Torch-MLIR it generates some garbage values for those indices and hence results in failure.

**Comment by vivekkhandelwal1** [comment]
> So the updated PyTorch decomposition is wrong now?

Yes

**Comment by vivekkhandelwal1** [comment]
I have created an issue in PyTorch: https://github.com/pytorch/pytorch/issues/94591
