### ISSUE TITLE
[MLIR] Fold slice+copy_ pattern None / INTMAX support 

### ISSUE THREAD

**Issue by AmosLewis** [llvm/torch-mlir#1953]
https://github.com/llvm/torch-mlir/pull/1901
I create a smallest test to recreate the slice+copy_ INTMAX issue: [test_intmax.py](https://gist.github.com/AmosLewis/b53dfecbe4918618031cac01c8a88fb9#file-test_intmax-py)

Besides, I also create a new python test module in torch_mlir to prove that this is not supported in torch_mlir.
The following is the module and the mlir file it generated.  
**Python SliceCloneModule_basic**
```
class SliceCloneModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    @export
    @annotate_args([
        None,
        ([-1, -1, -1], torch.float32, True),
    ])
    def forward(self, x):
        # TODO: remove hacky cat tensor once refbackend supports 0 size dim
        x_new = x.new_zeros(x.shape)  # tensor([[0, 0, 0, 0]])
        x_new[..., 1:] = x[..., :-1].clone()  # tensor([[6536,  504,   24]])
        return x_new

@register_test_case(module_factory=lambda: SliceCloneModule())
def SliceCloneModule_basic(module, tu: TestUtils):
    module.forward(tu.rand(1, 4))

```
Here is the python test result:
**TOSA:**
```
python -m e2e_testing.main -c tosa -f "SliceCloneModule_basic" -v
XFAIL - "SliceCloneModule_basic"
Summary:
    Expectedly Failed: 1

```
**LINALG:**
```
python -m e2e_testing.main -c linalg -f "SliceCloneModule_basic" -v
FAIL - "SliceCloneModule_basic"

Unexpected outcome summary:

****** Failed tests - 1 tests
    FAIL - "SliceCloneModule_basic"
        Compilation error: Traceback (most recent call last):
          File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/framework.py", line 290, in compile_and_run_test
            compiled = config.compile(test.program_factory())
          File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/linalg_on_tensors_backend.py", line 33, in compile
            module = torch_mlir.compile(
          File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 371, in compile
            run_pipeline_with_repro_report(
          File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
            raise TorchMlirCompilerError(trimmed_message) from None
        torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
        error: unsupported by backend contract: tensor with unknown rank
        note: see current operation: %11 = "torch.tensor_static_info_cast"(%10) : (!torch.vtensor<[?,?,?],f32>) -> !torch.vtensor<*,f32>
        note: this is likely due to a missing transfer function in abstract_interp_lib_gen.py

        For Torch-MLIR developers, the error can be reproduced with:
        $ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints})' /tmp/SliceCloneModule.mlir
        Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
Summary:
    Failed: 1
```
**debug print mlir file:**
```
#loc = loc(unknown)
module attributes {torch.debug_module_name = "SliceCloneModule"} {
  func.func private @__torch__.torch_mlir_e2e_test.test_suite.slice_like.SliceCloneModule.forward(%arg0: !torch.nn.Module<"__torch__.torch_mlir_e2e_test.test_suite.slice_like.SliceCloneModule"> loc(unknown), %arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[?,?,?],f32>} loc(unknown)) -> !torch.tensor {
    %false = torch.constant.bool false loc(#loc)
    %int-1 = torch.constant.int -1 loc(#loc1)
    %none_0 = torch.constant.none loc(#loc)
    %int1 = torch.constant.int 1 loc(#loc2)
    %1 = torch.aten.size %arg1 : !torch.tensor -> !torch.list<int> loc(#loc3)
    %2 = torch.aten.new_zeros %arg1, %1, %none_0, %none_0, %none_0, %none_0 : !torch.tensor, !torch.list<int>, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.tensor loc(#loc4)
    %3 = torch.aten.slice.Tensor %arg1, %int-1, %none_0, %int-1, %int1 : !torch.tensor, !torch.int, !torch.none, !torch.int, !torch.int -> !torch.tensor loc(#loc1)
    %4 = torch.aten.clone %3, %none_0 : !torch.tensor, !torch.none -> !torch.tensor loc(#loc1)
    %5 = torch.aten.slice.Tensor %2, %int-1, %int1, %none_0, %int1 : !torch.tensor, !torch.int, !torch.int, !torch.none, !torch.int -> !torch.tensor loc(#loc5)
    %6 = torch.aten.copy_ %5, %4, %false : !torch.tensor, !torch.tensor, !torch.bool -> !torch.tensor loc(#loc5)
    return %2 : !torch.tensor loc(#loc)
  } loc(#loc)
  torch.class_type @__torch__.torch_mlir_e2e_test.test_suite.slice_like.SliceCloneModule {
    torch.attr private "training" : !torch.bool loc(#loc)
    torch.attr private "_is_full_backward_hook" : !torch.optional<bool> loc(#loc)
    torch.method "forward", @__torch__.torch_mlir_e2e_test.test_suite.slice_like.SliceCloneModule.forward loc(#loc)
  } loc(#loc)
  %true = torch.constant.bool true loc(#loc)
  %none = torch.constant.none loc(#loc)
  %0 = torch.nn_module {
    torch.slot "training", %true : !torch.bool loc(#loc)
    torch.slot "_is_full_backward_hook", %none : !torch.none loc(#loc)
  } : !torch.nn.Module<"__torch__.torch_mlir_e2e_test.test_suite.slice_like.SliceCloneModule"> loc(#loc)
} loc(#loc)
#loc1 = loc("/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/slice_like.py":88:25)
#loc2 = loc("/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/slice_like.py":88:34)
#loc3 = loc("<string>":13:9)
#loc4 = loc("/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/slice_like.py":87:16)
#loc5 = loc("/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/slice_like.py":88:8)
```

There is a difference that needs to be noticed. 
The input **end** of the **slice** op is different between the **make_fx** fx graph print( **INT_MAX 9223372036854775807**) in  [test_intmax.py](https://gist.github.com/AmosLewis/b53dfecbe4918618031cac01c8a88fb9#file-test_intmax-py) and the **torch_mlir** python module mlir debug print (**%none_0** ).
    %slice_2 : [#users=1] = call_function[target=torch.ops.aten.slice.Tensor](args = (%new_zeros, 1, 1, **9223372036854775807**), kwargs = {})
**VS**
    %5 = torch.aten.slice.Tensor %2, %int-1, %int1, **%none_0**, %int1 : !torch.tensor, !torch.int, !torch.int, !torch.none, !torch.int -> !torch.tensor loc(#loc5)

**Comment by AmosLewis** [comment]
Tried to add end support for INT64_MAX
```
    if (end < 0) {
      Value dimSize = rewriter.create<AtenSizeIntOp>(
          op.getLoc(), sliceOp.getSelf(), sliceOp.getDim());
      newEnd =
          rewriter.create<AtenAddIntOp>(op.getLoc(), dimSize, sliceOp.getEnd());
      newEnd.dump();
    } else if (end == INT64_MAX){
      Value newEnd = rewriter.create<AtenSizeIntOp>(
          op.getLoc(), sliceOp.getSelf(), sliceOp.getDim());
      newEnd.dump(); // %7 = torch.aten.size.int %3, %int1 : !torch.tensor, !torch.int -> !torch.int
    }
```
-> same error
`<unknown>:0: error: invalid size -9223372036854775808 for !torch.tensor type`

**Comment by gpetters94** [comment]
If I'm understanding this correctly, wouldn't the solution be to just clamp the start/end values to the input size during or immediately after the shape calculation step?

**Comment by AmosLewis** [comment]
> > Tried to add end support for INT64_MAX
> > ```
> >     if (end < 0) {
> >       Value dimSize = rewriter.create<AtenSizeIntOp>(
> >           op.getLoc(), sliceOp.getSelf(), sliceOp.getDim());
> >       newEnd =
> >           rewriter.create<AtenAddIntOp>(op.getLoc(), dimSize, sliceOp.getEnd());
> >       newEnd.dump();
> >     } else if (end == INT64_MAX){
> >       Value newEnd = rewriter.create<AtenSizeIntOp>(
> >           op.getLoc(), sliceOp.getSelf(), sliceOp.getDim());
> >       newEnd.dump(); // %7 = torch.aten.size.int %3, %int1 : !torch.tensor, !torch.int -> !torch.int
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -> same error `<unknown>:0: error: invalid size -9223372036854775808 for !torch.tensor type`
> 
> Do you have a WIP patch I can look at? It helps having the context of the surrounding code.

https://github.com/llvm/torch-mlir/pull/1970/files

**Comment by ramiro050** [comment]
I don't think your changes are the cause of the error. This might be hitting a bug elsewhere. Do you have a small reproducible example?

**Comment by AmosLewis** [comment]
> t5_small_torchscript_test.mlir

Yes. [t5_small_torchscript_test.mlir](https://gist.github.com/AmosLewis/20895fa06e8b61ce83e9a2b9c2ee8ca6#file-t5_small_torchscript_test-mlir)

Got a patch to fix the int64_max, but go back to the original slice and copy shape * issue. https://github.com/llvm/torch-mlir/pull/1970

**Comment by AmosLewis** [comment]
> I don't think your changes are the cause of the error. This might be hitting a bug elsewhere. Do you have a small reproducible example?

Yes. Here is the small reproducible mlir example. [t5_small_torchscript_test.mlir](https://gist.github.com/AmosLewis/20895fa06e8b61ce83e9a2b9c2ee8ca6#file-t5_small_torchscript_test-mlir)

Got a patch to fix the int64_max, but go back to the original slice and copy shape * issue. https://github.com/llvm/torch-mlir/pull/1970

**Comment by gpetters94** [comment]
> > I don't think your changes are the cause of the error. This might be hitting a bug elsewhere. Do you have a small reproducible example?
> 
> Yes. Here is the small reproducible mlir example. [t5_small_torchscript_test2.mlir](https://gist.github.com/AmosLewis/d960c815d3de2f68949615c683cafca1)
> 
> Got a patch to fix the int64_max, but go back to the original slice and copy shape * issue. #1970

The fix is [here](https://github.com/gpetters94/mlir-npcomp/tree/intmax). It looks like the new issue is coming from the `masked_fill_`

**Comment by AmosLewis** [comment]
Success: [test_slicecopy.py](https://gist.github.com/AmosLewis/c6007c2154fedd51081faaee903a1b2c#file-test_slicecopy-py)
FAIL: [test_maked_fill.py](https://gist.github.com/AmosLewis/85b7c19409bfdbe45f216d689e947578#file-test_maked_fill-py)
