### ISSUE TITLE
 Test against the most recent stable version of PyTorch

### ISSUE THREAD

**Issue by ljfitz** [llvm/torch-mlir#2025]
In the weekly meeting of 27 March we discussed adding a test of torch-mlir built and run with the most recent stable PyTorch version. The expectation was that the torchscript path is likely to work, while newer paths may not.
We're investigating adding this to testing by:

- adding `torch-version` to the [buildAndTest.yml matrix](https://github.com/llvm/torch-mlir/blob/72c3326097140726f7b31a75e62f40d5e3df86d2/.github/workflows/buildAndTest.yml#L27)
- renaming [pytorch-requirements.txt](https://github.com/llvm/torch-mlir/blob/72c3326097140726f7b31a75e62f40d5e3df86d2/https://github.com/llvm/torch-mlir/blob/72c3326097140726f7b31a75e62f40d5e3df86d2/pytorch-requirements.txt#L3#L3) to `pytorch-nightly-requirements.txt` and add `pytorch-stable-requirements.txt`
- passing the version by env. variable to scripts like [build_linux_packages.sh](https://github.com/llvm/torch-mlir/blob/72c3326097140726f7b31a75e62f40d5e3df86d2/.github/workflows/buildAndTest.yml#L101) and adjust to use the appropriate `pytorch-requirements.txt` file.

So far this seems to be successful at building and running tests, and we're starting to see what is failing - see https://github.com/llvm/torch-mlir/issues/2025#issuecomment-1517673883:
- :::: Run Lazy Tensor Core e2e integration tests:
  - Passed: 699
  - Expectedly Failed: 143
  - **Unexpectedly Passed: 24**
- :::: Run TorchDynamo e2e integration tests
  - Passed: 17
  - **Failed: 809**
  - Expectedly Failed: 40
- torch-mlir-dialects regression:
  - Failed Tests (1): TORCH_MLIR_PYTHON :: debug/lockstep_basic.py (TorchDynamo related)
- `update_abstract_interp_lib.sh` and `update_torch_ods.sh` mismatches

(Note: I see somewhat related discussion in https://github.com/llvm/torch-mlir/issues/1009, but the suggestion from the meeting to add an item to the test matrix seems new enough to make a separate issue.)

**Comment by silvasean** [comment]
Hey Liam, thanks for doing this. Is there an actionable next step here? Do we want to add a non-blocking presubmit for this already and declare a burndown on the remaining issues?

**Comment by maxbartel** [comment]
Hi!
Here is a summary of the failures:
```
torch-mlir-dialects regression:
Failed Tests (1):
  TORCH_MLIR_PYTHON :: debug/lockstep_basic.py

Lazy Tensor Core e2e:
****** Unexpectedly Passed tests - 24 tests
    XPASS - "BernoulliFloatModule_basic"
    XPASS - "BernoulliModule_basic"
    XPASS - "BernoulliPModule_basic"
    XPASS - "DropoutTrainModule_basic"
    XPASS - "StdCorrectionKeepDimModule_basic"
    XPASS - "StdCorrectionNoneModule_basic"
    XPASS - "VarBiasedModule_basic"
    XPASS - "VarCorrectionAllDimReduceModule_basic"
    XPASS - "VarCorrectionEmptyDimModule_basic"
    XPASS - "VarCorrectionKeepDimModule_basic"
    XPASS - "VarCorrectionLargeInputModule_basic"
    XPASS - "VarCorrectionModule_basic"
    XPASS - "VarCorrectionNoneModule_basic"
    XPASS - "VarCorrectionSingleDimReduceModule_basic"
    XPASS - "VarDimAllDimReduceModule_basic"
    XPASS - "VarDimBiasedModule_basic"
    XPASS - "VarDimEmptyDimModule_basic"
    XPASS - "VarDimModule_basic"
    XPASS - "VarDimMultiDimModule_basic"
    XPASS - "VarDimNegativeModule_basic"
    XPASS - "VarDimNoneDimModule_basic"
    XPASS - "VarDimSingleDimModule_basic"
    XPASS - "VarDimUnbiasedModule_basic"
    XPASS - "VarUnbiasedModule_basic"

TorchDynamo e2e:
 ****** Failed tests - 809 tests

:::: Check that update_abstract_interp_lib.sh has been run
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py", line 1211, in <module>
    main(_create_argparse().parse_args())
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py", line 1148, in main
    asm = generate_library(globals())
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/library_generator.py", line 168, in generate_library
    _verify_signature_matches_registry(v, registry)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/library_generator.py", line 156, in _verify_signature_matches_registry
    raise ValueError(f"Signature mismatch for {f.__name__!r}: expected {expected_signature!r}, got {signature!r}")
ValueError: Signature mismatch for 'prims〇var〡shape': expected 'def prims〇var〡shape(inp: List[int], dims: Optional[List[int]], correction: int, output_dtype: Optional[int] = None) -> List[int]:', got 'def prims〇var〡shape(inp: List[int], dims: Optional[List[int]], correction: float, output_dtype: Optional[int] = None) -> List[int]:'
:::: Check that update_torch_ods.sh has been run
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py", line 749, in <module>
    main(args)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py", line 725, in main
    emit_ops(emitter_td, registry)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py", line 419, in emit_ops
    emit("aten::std.correction : (Tensor, int[]?, Scalar?, bool) -> (Tensor)")
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py", line 225, in emit
    emit_op(registry[key], emitter_td, **kwargs)
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/build_tools/registry.py", line 394, in __getitem__
    return self.by_unique_key[key]
KeyError: 'aten::std.correction : (Tensor, int[]?, Scalar?, bool) -> (Tensor)'
```

For more details you can take a look at the pipeline logs.

**Comment by silvasean** [comment]
cc @ramiro050

**Comment by ramiro050** [comment]
> The torchdynamo errors seem to be caused by this line here:
> 
> https://github.com/llvm/torch-mlir/blob/c76a48308e17dc6a91c9b07f0adc96053e411c44/python/torch_mlir/dynamo.py#L65
> 
> It seems that PyTorch stable does not have the op `aten._native_batch_norm_legit_no_training`. Removing it should fix most, if not all, the failures.

I locally removed this line, and the test suite for dynamo using the nightly PyTorch was unaffected by it, so it should be okay to remove this line in your patch, @maxbartel.

**Comment by mgehre-amd** [comment]
I think we can close this issue, right?

**Comment by powderluv** [comment]
Yes please
