### ISSUE TITLE
`ninja all install` does not install _jit_ir_importer binaries/packages

### ISSUE THREAD

**Issue by agostini01** [llvm/torch-mlir#2121]
Hi, after building, installing, and exporting libs with:
```
export PYTHONPATH=:/opt/llvm-project/python_packages/mlir_core:/installs/torch-mlir/python_packages/torch_mlir
```
I get an error stating that: `ModuleNotFoundError: No module named 'torch_mlir._mlir_libs._jit_ir_importer'`

If I export the build folder as suggested in the [Development.md file](https://github.com/llvm/torch-mlir/blob/main/docs/development.md#linux-and-macos), I have no issues.
```
export PYTHONPATH=:/opt/llvm-project/python_packages/mlir_core:/builds/torch-mlir/tools/torch-mlir/python_packages/torch_mlir
```

`ninja check-torch-mlir-all` passes tests (if on green checkmark commit). 

One of the missing files that fails to install is here:
```
/builds/torch-mlir/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/_jit_ir_importer.cpython-38-x86_64-linux-gnu.so
```

How can I install the missing libraries?

My actual project depends on an older version of torch-mlir which does not have published torch-mlir python whees. Directions on generating wheels that include the missing libraries would also be appreciated.

---

Commands to reproduce:

```
# clone torch-mlir, initialize submodules and compile with...

mkdir -p /builds/torch-mlir /installs/torch-mlir && \
cmake -GNinja \
    -B/builds/torch-mlir \
    -H/torch_mlir_src/externals/llvm-project/llvm \
    -DCMAKE_INSTALL_PREFIX=/installs/torch-mlir \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DLLVM_ENABLE_PROJECTS=mlir \
    -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
    -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=/torch_mlir_src \
    -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=/torch_mlir_src/externals/llvm-external-projects/torch-mlir-dialects \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_TARGETS_TO_BUILD=host \
    -DTORCH_MLIR_ENABLE_JIT_IR_IMPORTER=1 && \
cd /builds/torch-mlir && \
ninja tools/torch-mlir/all install
```

Added `-DTORCH_MLIR_ENABLE_JIT_IR_IMPORTER=1` just to make sure it is on. It seems to be default to be `on`.

```
python -c "import sys; print('\n'.join(sys.path))"
```

```
/builds/torch-mlir
/opt/llvm-project/python_packages/mlir_core
/installs/torch-mlir/python_packages/torch_mlir
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
(reverse-i-search)`-c': python ^C "import sys; print('\n'.join(sys.path))"
```

```
python -c "import torch_mlir"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/installs/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 18, in <module>
    from torch_mlir.dialects.torch.importer.jit_ir import ClassAnnotator, ImportOptions, ModuleBuilder
  File "/installs/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/importer/jit_ir/__init__.py", line 14, in <module>
    from ....._mlir_libs._jit_ir_importer import *
ModuleNotFoundError: No module named 'torch_mlir._mlir_libs._jit_ir_importer'
```

**Comment by agostini01** [comment]
For anyone running into a similar issue, after following the tutorial, I took advantage of the `TORCH_MLIR_CMAKE_BUILD_DIR_ALREADY_BUILT=1` flag, built python packges locally `CMAKE_GENERATOR=Ninja python setup.py bdist_wheel`, and moved to the desired location.

Note, the install issue is still present and this is a workaround.

```
    git init /torch_mlir_src && \
    cd /torch_mlir_src && \
    git remote add origin ${TORCHMLIR_URL} && \
    git fetch --depth=1 origin ${TORCHMLIR_COMMIT} && \
    git reset --hard ${TORCHMLIR_COMMIT} && \
    git submodule init && \
    git submodule update --depth=1 --recursive

    mkdir -p /builds/torch-mlir /installs/torch-mlir && \
    cmake -GNinja \
        -B/builds/torch-mlir \
        -H/torch_mlir_src/externals/llvm-project/llvm \
        -DCMAKE_INSTALL_PREFIX=/installs/torch-mlir \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER_LAUNCHER=ccache \
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DLLVM_ENABLE_PROJECTS=mlir \
        -DLLVM_EXTERNAL_PROJECTS="torch-mlir;torch-mlir-dialects" \
        -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR=/torch_mlir_src \
        -DLLVM_EXTERNAL_TORCH_MLIR_DIALECTS_SOURCE_DIR=/torch_mlir_src/externals/llvm-external-projects/torch-mlir-dialects \
        -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
        -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_TARGETS_TO_BUILD=host && \
    cd /builds/torch-mlir && \
    ninja tools/torch-mlir/all

# Torch-MLIR install is missing packages
# For now, this will copy the files into the same location as they would be installed
    cd /torch_mlir_src && \
    CMAKE_GENERATOR=Ninja \
    TORCH_MLIR_CMAKE_BUILD_DIR=/builds/torch-mlir \
    TORCH_MLIR_CMAKE_BUILD_DIR_ALREADY_BUILT=1 \
    TORCH_MLIR_PYTHON_PACKAGE_VERSION=20231215 \
    python setup.py bdist_wheel && \
    mkdir -p /installs/torch-mlir/python_packages && \
    cp -R /torch_mlir_src/build/lib.linux-x86_64-cpython-38 /installs/torch-mlir/python_packages/torch_mlir
```
