### ISSUE TITLE
Running unit tests

### ISSUE THREAD

**Issue by chelini** [llvm/torch-mlir#2211]
Hi All,
I am following `development.md` to set up torch-mlir. I can compile, but when I run the tests most of them fail. I am running `cmake --build build --target check-torch-mlir`. The tests that fail are:

```
Failed Tests (47):
  TORCH_MLIR :: CAPI/torch.c
  TORCH_MLIR :: python/custom_op_shape_dtype_fn.py
  TORCH_MLIR :: python/importer/jit_ir/get_registered_ops.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/arg-error.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/arg-tensor-type-bound.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/class-annotator-repr.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/export-error.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/export-recursive.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/annotations/export.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/debug-module-name.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/dict.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/functions-that-call-methods.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/functions.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/list.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/methods-derefine.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/methods-locations.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/methods.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/object-identity-error-submodule.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/object-identity-error.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/object-identity-torch-bug.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/object-identity.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/prim.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/primitives.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/strings.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/submodules-select.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/submodules.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/tensors-value-semantics.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/tensors.py
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/tuple.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/classes.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/debug-info.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/dict.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/elif.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/errors.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/function-block-arg-adjustment.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/function-derefine.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/if.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/list.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/loop.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/prim.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/tuple.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/types-bool.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/types-none.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/unimplemented.py
  TORCH_MLIR :: python/importer/jit_ir/node_import/union.py
  TORCH_MLIR :: python/smoketest.py
```

And the error I see is:

```
Traceback (most recent call last):
  File "/home/lorenzo/torch-mlir/test/python/importer/jit_ir/node_import/debug-info.py", line 6, in <module>
    from torch_mlir.dialects.torch.importer.jit_ir import ModuleBuilder
  File "/home/lorenzo/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 13, in <module>
    from torch._functorch.compile_utils import strip_overloads
ModuleNotFoundError: No module named 'torch._functorch'
```

Any idea? Thanks.

**Comment by chelini** [comment]
> Did you install the correct nightly torch version via `pip install -r requirements.txt`?

Yes, I did it. Right after cloning the repo I ran what mentioned in this section: https://github.com/llvm/torch-mlir/blob/main/docs/development.md#setup-your-python-virtualenvironment-and-dependencies

**Comment by chelini** [comment]
```
(mlir_venv) ~/torch-mlir# pip install -r requirements.txt              
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Requirement already satisfied: torch==2.1.0.dev20230605 in ./mlir_venv/lib/python3.10/site-packages (from -r pytorch-requirements.txt (line 3)) (2.1.0.dev20230605+cpu)
Requirement already satisfied: numpy in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 1)) (1.25.0rc1)
Requirement already satisfied: pybind11 in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 2)) (2.10.4)
Requirement already satisfied: wheel in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 3)) (0.40.0)
Requirement already satisfied: setuptools in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 4)) (59.6.0)
Requirement already satisfied: cmake in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 5)) (3.26.3)
Requirement already satisfied: ninja in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 6)) (1.11.1)
Requirement already satisfied: packaging in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 7)) (23.1)
Requirement already satisfied: pyyaml in ./mlir_venv/lib/python3.10/site-packages (from -r build-requirements.txt (line 11)) (6.0)
Requirement already satisfied: pillow in ./mlir_venv/lib/python3.10/site-packages (from -r test-requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: dill in ./mlir_venv/lib/python3.10/site-packages (from -r test-requirements.txt (line 2)) (0.3.6)
Requirement already satisfied: multiprocess in ./mlir_venv/lib/python3.10/site-packages (from -r test-requirements.txt (line 3)) (0.70.14)
Requirement already satisfied: filelock in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (3.12.0)
Requirement already satisfied: typing-extensions in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (4.6.3)
Requirement already satisfied: sympy in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (1.12)
Requirement already satisfied: networkx in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (3.1)
Requirement already satisfied: jinja2 in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (3.1.2)
Requirement already satisfied: fsspec in ./mlir_venv/lib/python3.10/site-packages (from torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (2023.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./mlir_venv/lib/python3.10/site-packages (from jinja2->torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in ./mlir_venv/lib/python3.10/site-packages (from sympy->torch==2.1.0.dev20230605->-r pytorch-requirements.txt (line 3)) (1.3.0)
```
Looks like the requirements are there.

**Comment by chelini** [comment]
> Does the cmake cache point to the python binary of the virtual env into which you installed the requirements?

No, I got that wrong. Sorry by bad, all good. Closing this issue.
