### ISSUE TITLE
misunderstanding on ConvTranspose1d/2d/3d op?

### ISSUE THREAD

**Issue by sungin-h** [llvm/torch-mlir#2279]
Hi, 

AFAIK, ConvTranspose means transpose(inverse) of Convolution rather than Convolution with transposed input tensor.
However, torch-mlir decomposes aten.conv_transposed2d to aten.convolution.
(https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L1528)

Can you check this?

**Comment by sungin-h** [comment]
I compiled ConvTranspose2D+relu in torch and met error message as below

err msg:
Traceback (most recent call last):
  File "convTranspose2d_relu.py", line 29, in <module>
    module = torch_mlir.compile(model,input_tensor,output_type=torch_mlir.OutputType.TOSA)
  File "/usr/local/lib/python3.8/dist-packages/torch_mlir/__init__.py", line 444, in compile
    return _lower_mlir_module(verbose, output_type, mb.module)
  File "/usr/local/lib/python3.8/dist-packages/torch_mlir/__init__.py", line 276, in _lower_mlir_module
    run_pipeline_with_repro_report(
  File "/usr/local/lib/python3.8/dist-packages/torch_mlir/compiler_utils.py", line 75, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:

python exception: Failure while executing pass pipeline:
error: callsite(callsite("/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py":956:15 at "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py":217:20) at "convTranspose2d_relu.py":12:6): 'tensor.cast' op operand type 'tensor<1x3x16x32xf32>' and result type 'tensor<1x3x64x128xf32>' are cast incompatible
note: callsite(callsite("/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py":956:15 at "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py":217:20) at "convTranspose2d_relu.py":12:6): see current operation: %17 = "tensor.cast"(%16) : (tensor<1x3x16x32xf32>) -> tensor<1x3x64x128xf32>


The input tensor shape is [1, 3, 32, 64] and expected output tensor shape is [1, 3, 64, 128] where ConvTranspose2D(in_channel=3,out_channel=3,kernel_size=2,stride=2,padding=0)

To reproduce:
https://github.com/sungin-h/DL_ML/blob/main/torch/convTranspose2d_relu.py
https://github.com/sungin-h/DL_ML/blob/main/torch/NN.mlir

**Comment by ramiro050** [comment]
Thanks for the reproducer! Turns out that the [TorchToTosa lowering](https://github.com/llvm/torch-mlir/blob/bcbfeecae0fdaa7ea7871723f5f5026a65a7fdc8/lib/Conversion/TorchToTosa/TorchToTosa.cpp#L1834) for `aten.convolution` does not check the `transposed` flag when performing the lowering. Handling for the `transposed` case needs to be added.
