### ISSUE TITLE
Compile pytorch yolov5 model to MLIR failed

### ISSUE THREAD

**Issue by wynterr** [llvm/torch-mlir#2305]
Hi, I'm trying to use torch-mlir to compile a pytorch yolov5 model from https://github.com/ultralytics/yolov5 . However I'm encountering an error saying that operator "aten.upsample_nearest2d.vec" is not supported. This is a bit strange because it's a common operator. I wonder how could I fix this.

Full error log:

```
/home/ubuntu/xxx/workspace/yolov5/models/yolo.py:64: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
/home/ubuntu/xxx/workspace/yolov5/models/yolo.py:64: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:
Traceback (most recent call last):
  File "/home/ubuntu/xxx/workspace/yolov5/to_mlir.py", line 845, in <module>
    main(opt)
  File "/home/ubuntu/xxx/workspace/yolov5/to_mlir.py", line 840, in main
    run(**vars(opt))
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/xxx/workspace/yolov5/to_mlir.py", line 738, in run
    mlir = torch_mlir.compile(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch_mlir/__init__.py", line 438, in compile
    run_pipeline_with_repro_report(
  File "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch_mlir/compiler_utils.py", line 75, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch/nn/functional.py":3987:0: unsupported by backend contract: Unimplemented operator 'aten.upsample_nearest2d.vec'
note: "/home/ubuntu/anaconda3/envs/yolov5/lib/python3.11/site-packages/torch/nn/functional.py":3987:0: see current operation: %288 = "torch.operator"(%273, %287, %142) {name = "aten.upsample_nearest2d.vec"} : (!torch.tensor<[1,256,20,20],f32>, !torch.list<int>, !torch.none) -> !torch.tensor<[1,256,40,40],f32>

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints extra-library=})' /tmp/DetectionModel.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

Code to use torch_mlir:
```
 import numpy as np 
 import torch_mlir                                                                                                                                                                  
example_input = torch.from_numpy(np.fromfile('/home/ubuntu/xxx/workspace/data/images/0.bin','float32').reshape((1,3,640,640)))                            
mlir = torch_mlir.compile(
    model,
    example_input,
    output_type="linalg-on-tensors",
    use_tracing=True)
```

Environment:
python 3.11
torch                    2.1.0.dev20230704+cpu
torch-mlir               20230705.890
torchvision              0.16.0.dev20230704+cpu

**Comment by RiRi114** [comment]
hi，Is your problem solved？

**Comment by RiRi114** [comment]
My code to use torch_mlir:

**Comment by RiRi114** [comment]
My code to use torch_mlir:
import torch
import torch_mlir
model = torch.hub.load("ultralytics/yolov5", "yolov5s")
module = torch_mlir.compile(model, torch.ones(1, 3, 224, 224), output_type="linalg-on-tensors")

But also generate error:
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults

**Comment by RiRi114** [comment]
My code to use torch_mlir:
```
import torch
import torch_mlir
model = torch.hub.load("ultralytics/yolov5", "yolov5s")
module = torch_mlir.compile(model, torch.ones(1, 3, 224, 224), output_type="linalg-on-tensors")

```
But also generate error:
`torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults`
