### ISSUE TITLE
Issue with the Roll Pytorch CI

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#2472]
Hi, the Roll-PyTorch CI has been failing with the same error for the last 2 weeks. The [error](https://github.com/llvm/torch-mlir/actions/runs/6222927669/job/16887808677) is as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/main_checkout/torch-mlir/e2e_testing/main.py", line 43, in <module>
    register_all_tests()
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/__init__.py", line 31, in register_all_tests
    from . import vision_models
  File "/main_checkout/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/test_suite/vision_models.py", line 7, in <module>
    import torchvision.models as models
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 55, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_custom_ops.py", line 253, in inner
    custom_op = _find_custom_op(qualname, also_check_torch_library=True)
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_custom_op/impl.py", line 1076, in _find_custom_op
    overload = get_op(qualname)
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_custom_op/impl.py", line 1062, in get_op
    error_not_found()
  File "/main_checkout/torch-mlir/docker_venv/lib/python3.10/site-packages/torch/_custom_op/impl.py", line 1052, in error_not_found
    raise ValueError(
ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.
Error: Process completed with exit code 1.
```

On the other hand, if we create a [separate PR](https://github.com/llvm/torch-mlir/pull/2471) with the updated torch version then it won't result in this failure. Also, the issue is not reported locally.

There's definitely an issue with the Roll PyTorch CI causing this error on a daily basis.

**Comment by vivekkhandelwal1** [comment]
> Isn't this the same issue that you filed upstream with torchvision ?

This one https://github.com/pytorch/vision/issues/7472?

**Comment by powderluv** [comment]
ah yeah that isn't the same

**Comment by ashay** [comment]
Sorry about the delayed response.  I'll take a look at this over the weekend.
