### ISSUE TITLE
Cannot access storage of SparseTensorImpl

### ISSUE THREAD

**Issue by luo-yicong** [llvm/torch-mlir#2587]
Hi, when trying use torch-mlir complie whisper, i meet the error as follow：
```shell
/usr/local/lib/python3.11/dist-packages/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
Traceback (most recent call last):
  File "/workspace/iree_dev/code/pytorch_whisper.py", line 9, in <module>
    module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 437, in compile
    raise Exception(f"""
Exception: 
PyTorch TorchScript module -> torch-mlir Object Graph IR import failed with:
### Importer C++ Exception:
Cannot access storage of SparseTensorImpl
### Importer Diagnostics:
``` 

The script as follows
```python
import torch
import whisper
import torch_mlir

model = whisper.load_model("tiny")
model.to("cpu")
model.eval()
a ,b= torch.rand(1,80,3000).to(torch.float32),torch.randint(1,10,(1,448)).to(torch.int32)
module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)

with open("./pytorch_whisper_tiny.mlir", "w", encoding="utf-8") as outf:
    outf.write(str(module))
```

**Comment by ramiro050** [comment]
This type of importer error *usually* means that the PyTorch version you're using is not the one that Torch-MLIR expects. How are you installing Torch-MLIR?

**Comment by luo-yicong** [comment]
I used the following command to install Torch-MLIR
```
pip install --pre torch-mlir torchvision \
  -f https://llvm.github.io/torch-mlir/package-index/ \
  --extra-index-url https://download.pytorch.org/whl/nightly/cpu
``` 
the versions of torch-mlir and pytorch are as follows：
```
torch               2.2.0.dev20231115+cpu
torch-mlir          20231127.1035
``` 
I solved this problem by modifying the source code of whisper
```python
# before modification
self.register_buffer("alignment_heads", all_heads.to_sparse(), persistent=False)
# after modification
self.register_buffer("alignment_heads", all_heads, persistent=False)

# before modification
self.register_buffer("alignment_heads", mask.to_sparse(), persistent=False)
# after modification
self.register_buffer("alignment_heads", mask, persistent=False)
``` 
Then I ran into the problem of not supporting 1D convolution, and I modified whisper's source code to use 2D convolution instead of 1D convolution to solve the problem.

And then I ran into this problem.
```
/usr/local/lib/python3.11/dist-packages/whisper/model.py:181: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
Traceback (most recent call last):
  File "/workspace/iree_dev/code/whisper/pytorch_whisper.py", line 17, in <module>
    module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 457, in compile
    return _lower_mlir_module(verbose, output_type, mb.module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 291, in _lower_mlir_module
    run_pipeline_with_repro_report(
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/compiler_utils.py", line 69, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: "__module.encoder/__module.encoder.blocks.0/__module.encoder.blocks.0.attn/aten::pow"("/usr/local/lib/python3.11/dist-packages/torch/_tensor.py":40:0): 'arith.fptosi' op result #0 must be signless-fixed-width-integer-like, but got 'si64'
note: "__module.encoder/__module.encoder.blocks.0/__module.encoder.blocks.0.attn/aten::pow"("/usr/local/lib/python3.11/dist-packages/torch/_tensor.py":40:0): see current operation: %11874 = "arith.fptosi"(%362) : (f64) -> si64

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-linalg-on-tensors-backend-pipeline)' /tmp/Whisper.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
``` 
The script is as follows
```python
import torch
import whisper
import torch_mlir

model = whisper.load_model("tiny")
model.eval()

a ,b= torch.rand(1,80,3000).to(torch.float32),torch.randint(1,10,(1,448)).to(torch.int32)
module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)

with open("./pytorch_whisper_tiny.mlir", "w", encoding="utf-8") as outf:
    outf.write(str(module))
```

**Comment by luo-yicong** [comment]
> This type of importer error _usually_ means that the PyTorch version you're using is not the one that Torch-MLIR expects. How are you installing Torch-MLIR?


I used the following command to install Torch-MLIR
```
pip install --pre torch-mlir torchvision \
  -f https://llvm.github.io/torch-mlir/package-index/ \
  --extra-index-url https://download.pytorch.org/whl/nightly/cpu
``` 
the versions of torch-mlir and pytorch are as follows：
```
torch               2.2.0.dev20231115+cpu
torch-mlir          20231127.1035
``` 
I solved this problem by modifying the source code of whisper
```python
# before modification
self.register_buffer("alignment_heads", all_heads.to_sparse(), persistent=False)
# after modification
self.register_buffer("alignment_heads", all_heads, persistent=False)

# before modification
self.register_buffer("alignment_heads", mask.to_sparse(), persistent=False)
# after modification
self.register_buffer("alignment_heads", mask, persistent=False)
``` 
Then I ran into the problem of not supporting 1D convolution, and I modified whisper's source code to use 2D convolution instead of 1D convolution to solve the problem.

And then I ran into this problem.
```
/usr/local/lib/python3.11/dist-packages/whisper/model.py:181: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
Traceback (most recent call last):
  File "/workspace/iree_dev/code/whisper/pytorch_whisper.py", line 17, in <module>
    module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 457, in compile
    return _lower_mlir_module(verbose, output_type, mb.module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 291, in _lower_mlir_module
    run_pipeline_with_repro_report(
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/compiler_utils.py", line 69, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> Linalg-on-Tensors Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: "__module.encoder/__module.encoder.blocks.0/__module.encoder.blocks.0.attn/aten::pow"("/usr/local/lib/python3.11/dist-packages/torch/_tensor.py":40:0): 'arith.fptosi' op result #0 must be signless-fixed-width-integer-like, but got 'si64'
note: "__module.encoder/__module.encoder.blocks.0/__module.encoder.blocks.0.attn/aten::pow"("/usr/local/lib/python3.11/dist-packages/torch/_tensor.py":40:0): see current operation: %11874 = "arith.fptosi"(%362) : (f64) -> si64

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torch-backend-to-linalg-on-tensors-backend-pipeline)' /tmp/Whisper.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
``` 
The script is as follows
```python
import torch
import whisper
import torch_mlir

model = whisper.load_model("tiny")
model.eval()

a ,b= torch.rand(1,80,3000).to(torch.float32),torch.randint(1,10,(1,448)).to(torch.int32)
module = torch_mlir.compile(model, [a,b], output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)

with open("./pytorch_whisper_tiny.mlir", "w", encoding="utf-8") as outf:
    outf.write(str(module))
```

**Comment by ramiro050** [comment]
> And then I ran into this problem.

When you get this error, a temporary mlir file is created (`/tmp/Whisper.mlir` in your case). Can you share the contents of this file? I can take a look to see what is going on.

**Comment by luo-yicong** [comment]
> > And then I ran into this problem.
> 
> When you get this error, a temporary mlir file is created (`/tmp/Whisper.mlir` in your case). Can you share the contents of this file? I can take a look to see what is going on.

Thanks for your reply！This is the mlir file. [Whisper.txt](https://github.com/llvm/torch-mlir/files/13556192/Whisper.txt)

I solved this problem by modifying the source code of whisper and I don't know why this is working.
```python
# before modification
scale = (n_state // self.n_head) ** -0.25
# after modification
import math
scale = math.pow((n_state // self.n_head),-0.25)
```

**Comment by ramiro050** [comment]
There is a bug in torch-mlir. I made a github issue to track it: https://github.com/llvm/torch-mlir/issues/2625. Using `math.pow` is probably changing the type of the first argument allowing it to work.

**Comment by shmily176** [comment]
> > > And then I ran into this problem.
> > 
> > 
> > When you get this error, a temporary mlir file is created (`/tmp/Whisper.mlir` in your case). Can you share the contents of this file? I can take a look to see what is going on.
> 
> Thanks for your reply！This is the mlir file. [Whisper.txt](https://github.com/llvm/torch-mlir/files/13556192/Whisper.txt)
> 
> I solved this problem by modifying the source code of whisper and I don't know why this is working.
> 
> ```python
> # before modification
> scale = (n_state // self.n_head) ** -0.25
> # after modification
> import math
> scale = math.pow((n_state // self.n_head),-0.25)
> ```

Hello, can you share your final mlir file? We urgently need it, but we also encounter conversion problems，thanks a lot
