### ISSUE TITLE
unsupported by backend contract: module initializers

### ISSUE THREAD

**Issue by luo-yicong** [llvm/torch-mlir#2599]
I encountered the following problem when converting vae encoder, part of stable diffusion
```
/usr/local/lib/python3.11/dist-packages/diffusers/models/resnet.py:260: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/usr/local/lib/python3.11/dist-packages/diffusers/models/resnet.py:266: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
Traceback (most recent call last):
  File "/workspace/iree_dev/code/stablediffusion/pytorch_sd.py", line 9, in <module>
    module = torch_mlir.compile(vae_encoder, torch.rand(1,3,512,512), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/__init__.py", line 451, in compile
    run_pipeline_with_repro_report(
  File "/usr/local/lib/python3.11/dist-packages/torch_mlir/compiler_utils.py", line 69, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:


python exception: Failure while executing pass pipeline:
error: unknown: unsupported by backend contract: module initializers
note: unknown: see current operation: "torch.initialize.global_slots"(%4, %5, %8, %9, %12, %13, %16, %17, %22, %23, %26, %27, %32, %33, %36, %37, %42, %43, %46, %47, %52, %53, %56, %57, %62, %63, %66, %67, %70, %71, %74, %75, %78, %79, %88, %89, %92, %93, %96, %97, %100, %101, %104, %105) <{slotSymNames = [@down_blocks.0.resnets.0.norm1.weight, @down_blocks.0.resnets.0.norm1.bias, @down_blocks.0.resnets.0.norm2.weight, @down_blocks.0.resnets.0.norm2.bias, @down_blocks.0.resnets.1.norm1.weight, @down_blocks.0.resnets.1.norm1.bias, @down_blocks.0.resnets.1.norm2.weight, @down_blocks.0.resnets.1.norm2.bias, @down_blocks.1.resnets.0.norm1.weight, @down_blocks.1.resnets.0.norm1.bias, @down_blocks.1.resnets.0.norm2.weight, @down_blocks.1.resnets.0.norm2.bias, @down_blocks.1.resnets.1.norm1.weight, @down_blocks.1.resnets.1.norm1.bias, @down_blocks.1.resnets.1.norm2.weight, @down_blocks.1.resnets.1.norm2.bias, @down_blocks.2.resnets.0.norm1.weight, @down_blocks.2.resnets.0.norm1.bias, @down_blocks.2.resnets.0.norm2.weight, @down_blocks.2.resnets.0.norm2.bias, @down_blocks.2.resnets.1.norm1.weight, @down_blocks.2.resnets.1.norm1.bias, @down_blocks.2.resnets.1.norm2.weight, @down_blocks.2.resnets.1.norm2.bias, @down_blocks.3.resnets.0.norm1.weight, @down_blocks.3.resnets.0.norm1.bias, @down_blocks.3.resnets.0.norm2.weight, @down_blocks.3.resnets.0.norm2.bias, @down_blocks.3.resnets.1.norm1.weight, @down_blocks.3.resnets.1.norm1.bias, @down_blocks.3.resnets.1.norm2.weight, @down_blocks.3.resnets.1.norm2.bias, @mid_block.attentions.0.group_norm.weight, @mid_block.attentions.0.group_norm.bias, @mid_block.resnets.0.norm1.weight, @mid_block.resnets.0.norm1.bias, @mid_block.resnets.0.norm2.weight, @mid_block.resnets.0.norm2.bias, @mid_block.resnets.1.norm1.weight, @mid_block.resnets.1.norm1.bias, @mid_block.resnets.1.norm2.weight, @mid_block.resnets.1.norm2.bias, @conv_norm_out.weight, @conv_norm_out.bias]}> : (!torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[128],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[256],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>, !torch.tensor<[512],f32>) -> ()
note: unknown: this is likely due to InlineGlobalSlots being unable to inline a global slot

For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=aten.flatten.using_ints extra-library=})' /tmp/Encoder.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
``` 

The script is as follows:
```
import torch
import torch_mlir
from diffusers import StableDiffusionPipeline
model_id = "/workspace/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float32)

vae_encoder = pipe.vae.encoder
vae_encoder.eval()
module = torch_mlir.compile(vae_encoder, torch.rand(1,3,512,512), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
with open("./pytorch_vae_encoder.mlir", "w", encoding="utf-8") as outf:
    outf.write(str(module))
```

**Comment by qingyunqu** [comment]
There exists `aten.group_norm` which torch-mlir doesn't support in this model:
```%133 = torch.operator "aten.group_norm"(%130, %int32, %132, %131, %float9.999990e-07, %true) : (!torch.tensor<[1,512,128,128],f32>, !torch.int, !torch.tensor, !torch.tensor, !torch.float, !torch.bool) -> !torch.tensor<[1,512,128,128],f32>```

It will be resolved when https://github.com/llvm/torch-mlir/pull/2591 merge.

**Comment by luo-yicong** [comment]
> There exists `aten.group_norm` which torch-mlir doesn't support in this model: `%133 = torch.operator "aten.group_norm"(%130, %int32, %132, %131, %float9.999990e-07, %true) : (!torch.tensor<[1,512,128,128],f32>, !torch.int, !torch.tensor, !torch.tensor, !torch.float, !torch.bool) -> !torch.tensor<[1,512,128,128],f32>`
> 
> It will be resolved when #2591 merge.

Thanks for your reply. 
Doesn't torch-mlir support stable diffusionl? Have you ever used torch-mlir to convert this model? 
I want to use torch-mlir to convert stable diffusion now. Do you have any suggestions?

**Comment by qingyunqu** [comment]
> > There exists `aten.group_norm` which torch-mlir doesn't support in this model: `%133 = torch.operator "aten.group_norm"(%130, %int32, %132, %131, %float9.999990e-07, %true) : (!torch.tensor<[1,512,128,128],f32>, !torch.int, !torch.tensor, !torch.tensor, !torch.float, !torch.bool) -> !torch.tensor<[1,512,128,128],f32>`
> > It will be resolved when #2591 merge.
> 
> Thanks for your reply. Doesn't torch-mlir support stable diffusionl? Have you ever used torch-mlir to convert this model? I want to use torch-mlir to convert stable diffusion now. Do you have any suggestions?

It depends on operator support in torch-mlir. There are not enough model e2e tests in torch-mlir now. It need time to perfect torch-mlir. You can learn how to add operator support to torch-mlir. It's not that hard.

**Comment by luo-yicong** [comment]
> > > There exists `aten.group_norm` which torch-mlir doesn't support in this model: `%133 = torch.operator "aten.group_norm"(%130, %int32, %132, %131, %float9.999990e-07, %true) : (!torch.tensor<[1,512,128,128],f32>, !torch.int, !torch.tensor, !torch.tensor, !torch.float, !torch.bool) -> !torch.tensor<[1,512,128,128],f32>`
> > > It will be resolved when #2591 merge.
> > 
> > 
> > Thanks for your reply. Doesn't torch-mlir support stable diffusionl? Have you ever used torch-mlir to convert this model? I want to use torch-mlir to convert stable diffusion now. Do you have any suggestions?
> 
> It depends on operator support in torch-mlir. There are not enough model e2e tests in torch-mlir now. It need time to perfect torch-mlir. You can learn how to add operator support to torch-mlir. It's not that hard.

Thank you very much for your reply!

**Comment by qingyunqu** [comment]
I successfully use this PR https://github.com/llvm/torch-mlir/pull/2591 to convert this model. You could wait for https://github.com/llvm/torch-mlir/pull/2591 to be merged.

**Comment by luo-yicong** [comment]
> I successfully use this PR #2591 to convert this model. You could wait for #2591 to be merged.

Thanks for the reply!!!
I tried to convert the model based on the latest commit, but ran into another ERROR. 
The version of torch-mlir is [torch-mlir snapshot snapshot-20231213.1051](https://github.com/llvm/torch-mlir/releases/tag/snapshot-20231213.1051)

```
python exception: Failure while executing pass pipeline:
error: "__module.up_blocks.0/__module.up_blocks.0.upsamplers.0/aten::upsample_nearest2d"("/usr/local/lib/python3.11/dist-packages/torch/nn/functional.py":4001:0): unsupported by backend contract: Unimplemented operator 'aten.upsample_nearest2d.vec'
note: "__module.up_blocks.0/__module.up_blocks.0.upsamplers.0/aten::upsample_nearest2d"("/usr/local/lib/python3.11/dist-packages/torch/nn/functional.py":4001:0): see current operation: %498 = "torch.operator"(%496, %2, %497) <{name = "aten.upsample_nearest2d.vec"}> : (!torch.tensor<[2,512,64,64],f32>, !torch.none, !torch.list<float>) -> !torch.tensor<[2,512,128,128],f32>
``` 

The script is as follows:

```python
import torch
import torch_mlir
from diffusers import StableDiffusionPipeline
model_id = "/data/models/stable-diffusion/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float32)

vae_decoder = pipe.vae.decoder
vae_decoder.eval()
module = torch_mlir.compile(vae_decoder, torch.rand(2,4,64,64), output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,use_tracing=True)
with open("./pytorch_vae_decoder.mlir", "w", encoding="utf-8") as outf:
    outf.write(str(module))
``` 
Have you ever encountered this error？
