### ISSUE TITLE
Failure while creating the ExecutionEngine on MacOS `aarch64`

### ISSUE THREAD

**Issue by rikhuijzer** [llvm/torch-mlir#2651]
I'm following the TorchScript ResNet18 demo from the [README](https://github.com/llvm/torch-mlir#torchscript-resnet18). After installing the dependencies and
```
$ pip install --pre torch-mlir torchvision -f https://llvm.github.io/torch-mlir/package-index/ --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```
the script crashes with the following stacktrace:
```
$ python torchscript_resnet18.py
load image from https://upload.wikimedia.org/wikipedia/commons/2/26/YellowLabradorLooking_new.jpg
/Users/rik/Downloads/torch-mlir-demo/venv/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/rik/Downloads/torch-mlir-demo/venv/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/rik/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100.0%
Failed to create a TargetMachine for the host
Traceback (most recent call last):
  File "/Users/rik/Downloads/torch-mlir-demo/torchscript_resnet18.py", line 73, in <module>
    jit_module = backend.load(compiled)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rik/Downloads/torch-mlir-demo/venv/lib/python3.11/site-packages/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py", line 206, in load
    return RefBackendInvoker(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rik/Downloads/torch-mlir-demo/venv/lib/python3.11/site-packages/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py", line 84, in __init__
    self.ee = ExecutionEngine(module)
              ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failure while creating the ExecutionEngine.
```
This is on MacOS Sonoma 14.2 with an Apple silicon (M2) chip, Python 3.11.6, virtualenv 20.25.0 and pip 23.3.1. Furthermore, it is in a separate `virtualenv`:
```
$ pip list
Package            Version
------------------ ------------------
certifi            2023.11.17
charset-normalizer 3.3.2
filelock           3.13.1
fsspec             2023.12.2
idna               3.6
Jinja2             3.1.2
MarkupSafe         2.1.3
mpmath             1.3.0
networkx           3.2.1
numpy              1.26.2
packaging          23.2
Pillow             10.1.0
pip                23.3.1
requests           2.31.0
setuptools         69.0.2
sympy              1.12
torch              2.2.0.dev20231204
torch-mlir         20231214.1052
torchvision        0.17.0.dev20231204
typing_extensions  4.9.0
urllib3            2.1.0
wheel              0.42.0
```

**Comment by rikhuijzer** [comment]
I've tried inside a Docker too now and that works 🥳 :

```
$ docker run --it --rm python:3.11 /bin/bash

$ python -m venv mlir_venv

$ source mlir_venv/bin/activate

$ pip install --upgrade pip
[...]
Successfully installed pip-23.3.1

$ pip install --pre torch-mlir torchvision   -f https://llvm.github.io/torch-mlir/package-index/   --extra-index-url https://download.pytorch.org/whl/nightly/cpu
[...]
Successfully installed MarkupSafe-2.1.3 certifi-2023.11.17 charset-normalizer-3.3.2 filelock-3.13.1 fsspec-2023.12.2 idna-3.6 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.2 packaging-23.2 pillow-10.1.0 requests-2.31.0 sympy-1.12 torch-2.2.0.dev20231204 torch-mlir-20231216.1054 torchvision-0.17.0.dev20231204 typing-extensions-4.9.0 urllib3-2.1.0

$ wget https://raw.githubusercontent.com/llvm/torch-mlir/main/projects/pt1/examples/torchscript_resnet18.py

$ python torchscript_resnet18.py
[...]
PyTorch prediction
[('Labrador retriever', 70.6567611694336), ('golden retriever', 4.98832368850708), ('Saluki, gazelle hound', 4.47743558883667)]
torch-mlir prediction
[('Labrador retriever', 70.65672302246094), ('golden retriever', 4.988325595855713), ('Saluki, gazelle hound', 4.477458953857422)]

**Comment by rikhuijzer** [comment]
I don't know much about Python, but it seems that the root cause of this verbose issue is that the MacOS aarch64 wheels are not generated?

Everything runs fine (without Docker) when following the build from source instructions at [development.md](https://github.com/llvm/torch-mlir/blob/main/docs/development.md).
