### ISSUE TITLE
Translate Llama-2-7b-hf to MLIR failed

### ISSUE THREAD

**Issue by FlintWangacc** [llvm/torch-mlir#3743]
I use the following script to translate the Llama-2-7b-hf to MLIR. But it failed.
```python
from transformers import AutoTokenizer, LlamaForCausalLM
from torch_mlir import fx
import torch

model = LlamaForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf")
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")

prompt = "What is the capital of France?"
inputs = tokenizer(prompt, return_tensors="pt")

print(f"Input shape: {inputs['input_ids'].shape}")

m = fx.export_and_import(model, torch.randn(1, 8), enable_ir_printing=True,
                         enable_graph_printing=True)
```
Here is the backtrace
```shell
user@host:directory$ python3 ./lamaExample.py
Traceback (most recent call last):
  File "/home/user/work/tinyLlama_0927/./lamaExample.py", line 15, in <module>
    m = fx.export_and_import(model, torch.randn(1, 8), enable_ir_printing=True,
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch_mlir/fx.py", line 73, in export_and_import
    prog = torch.export.export(f, args, kwargs, dynamic_shapes=dynamic_shapes)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/__init__.py", line 174, in export
    return _export(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/_trace.py", line 946, in wrapper
    raise e
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/_trace.py", line 929, in wrapper
    ep = fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/exported_program.py", line 88, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/_trace.py", line 1455, in _export
    aten_export_artifact = export_func(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/_trace.py", line 1060, in _strict_export
    gm_torch_level = _export_to_torch_ir(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/export/_trace.py", line 512, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1350, in inner
    result_traced = opt_f(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 421, in _fn
    return fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1078, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 456, in _convert_frame_assert
    return _compile(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_utils_internal.py", line 83, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 799, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 232, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 618, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1184, in transform_code_object
    transformations(instructions, code_options)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 177, in _fn
    return fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 564, in transform
    tracer.run()
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2450, in run
    super().run()
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 892, in run
    while self.step():
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 804, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 498, in wrapper
    return inner_fn(self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1511, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 742, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 408, in call_function
    return tx.inline_user_function_return(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 748, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2665, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2781, in inline_call_
    tracer.run()
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 892, in run
    while self.step():
File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 804, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 498, in wrapper
    return inner_fn(self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1499, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 742, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 342, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 91, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 748, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2665, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2781, in inline_call_
    tracer.run()
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 892, in run
    while self.step():
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 804, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 498, in wrapper
    return inner_fn(self, inst)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1458, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 742, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/nn_module.py", line 380, in call_function
    return wrap_fx_proxy(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1713, in wrap_fx_proxy
    return wrap_fx_proxy_cls(target_cls=TensorVariable, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 1798, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx, allow_non_graph_fake=True)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1854, in get_fake_value
    raise TorchRuntimeError(str(e)).with_traceback(e.__traceback__) from None
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1786, in get_fake_value
    ret_val = wrap_fake_exception(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1301, in wrap_fake_exception
    return fn()
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1787, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1922, in run_node
    raise RuntimeError(make_error_message(e)).with_traceback(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 1909, in run_node
    return nnmodule(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1060, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1449, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1144, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1689, in _dispatch_impl
    return decomposition_table[func](*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_prims_common/wrappers.py", line 265, in _fn
    result = fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 1179, in embedding
    return weight[indices]
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1060, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1449, in dispatch
    return self._cached_dispatch_impl(func, types, args, kwargs)
File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1152, in _cached_dispatch_impl
    output = self._dispatch_impl(func, types, args, kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_tensor.py", line 1729, in _dispatch_impl
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_impls.py", line 150, in dispatch_to_op_implementations_dict
    return op_implementations_dict[func](fake_mode, func, *args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_subclasses/fake_impls.py", line 549, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/_meta_registrations.py", line 2988, in meta_index_Tensor
    torch._check(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/__init__.py", line 1200, in _check
    _check_with(RuntimeError, cond, message)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/__init__.py", line 1183, in _check_with
    raise error_type(message_evaluated)
torch._dynamo.exc.TorchRuntimeError: Failed running call_module L__self___model_embed_tokens(*(FakeTensor(..., size=(1, 8)),), **{}):
tensors used as indices must be long, int, byte or bool tenso
from user code:
   File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1208, in forward
    outputs = self.model(
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/work/selfPython/ai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 974, in forward
    inputs_embeds = self.embed_tokens(input_ids)
```

**Comment by FlintWangacc** [comment]
I think this is an error happened when torch try to translate python code to torchscript.
Is Llama model not supported well by pytorch?
```shell
from user code:
   File "/home/hmsjwzb/work/selfPython/ai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1208, in forward
    outputs = self.model(
  File "/home/hmsjwzb/work/selfPython/ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1561, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hmsjwzb/work/selfPython/ai/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 974, in forward
    inputs_embeds = self.embed_tokens(input_ids)
```

**Comment by stellaraccident** [comment]
For issues with torch.export, please file an issue with pytorch.
