### ISSUE TITLE
Tensors with dim values of 0 can exist in pytorch but break RefBackend

### ISSUE THREAD

**Issue by dan-garvey** [llvm/torch-mlir#448]
Not even sure if this qualifies as an issue, but if a lowering results in a rank>1 tensor with a dim of 0, the refbackend will crash. I'm not certain a case where this actually occurs in a model exists? 
Below is an example of torch code that produces such a result. 
`
a =torch.randint(10, (5,5))

print(a)
tensor([[5, 7, 2, 6, 5],
[3, 5, 2, 1, 2],
[6, 9, 6, 7, 5],
[8, 3, 9, 6, 2],
[7, 9, 9, 3, 7]])
print(a[:0,:0])
tensor([], size=(0, 0), dtype=torch.int64)
`

The error that will happen:
Exception ignored on calling ctypes callback function: <function RefBackendInvoker.__init__.<locals>.consume_return_mrf32 at 0x7fefd87993a0>
Traceback (most recent call last):                                                                                                                                                                     
`  File "/home/dan/my_gits/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/linalg_on_tensors_backends/refbackend.py", line 46, in consume_return_mrf32
    self.result = unranked_memref_to_numpy(a, np.float32)                                                                                                                                              
  File "/home/dan/my_gits/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/runtime/np_to_memref.py", line 98, in unranked_memref_to_numpy                                       
    np_arr = np.ctypeslib.as_array(val[0].aligned, shape=val[0].shape)                                                                                                                                 
  File "/home/dan/my_gits/torch-mlir/mlir_venv/lib/python3.8/site-packages/numpy/ctypeslib.py", line 518, in as_array                                                                                  
    return asarray(obj)                                                                                                                                                                                
  File "/home/dan/my_gits/torch-mlir/mlir_venv/lib/python3.8/site-packages/numpy/core/_dtype_ctypes.py", line 106, in dtype_from_ctypes_type                                                           
    return _from_ctypes_array(t)                                                                                                                                                                       
  File "/home/dan/my_gits/torch-mlir/mlir_venv/lib/python3.8/site-packages/numpy/core/_dtype_ctypes.py", line 33, in _from_ctypes_array                                                                
    return np.dtype((dtype_from_ctypes_type(t._type_), (t._length_,)))                                                                                                                                 
  File "/home/dan/my_gits/torch-mlir/mlir_venv/lib/python3.8/site-packages/numpy/core/_dtype_ctypes.py", line 106, in dtype_from_ctypes_type
    return _from_ctypes_array(t)                                                                                                                                                                       
  File "/home/dan/my_gits/torch-mlir/mlir_venv/lib/python3.8/site-packages/numpy/core/_dtype_ctypes.py", line 33, in _from_ctypes_array
    return np.dtype((dtype_from_ctypes_type(t._type_), (t._length_,)))                             
ValueError: invalid itemsize in generic type tuple   `

**Comment by cathyzhyi** [comment]
The following test can reproduce this error as well
```
class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    @export
    @annotate_args([
        None,
        ([-1, -1, -1], torch.float32, True),
    ])
    def forward(self, x):
        return x


@register_test_case(module_factory=lambda: TestModule())
def TestModule_basic(module, tu: TestUtils):
    module.forward(torch.randn(0, 0, 0))
```

**Comment by silvasean** [comment]
Yeah, this is definitely an issue. Looks pretty painful to debug. My understanding is that the memref descriptors that we lower to can handle size 0 dimensions, so conceptually this should "just work". But Yi's test case makes me a bit scared. It's probably worth looking at the IR dumps in Yi's test case see if anything obvious is going wrong.

This doesn't need to be super high priority right now, since we really will be moving more towards using IREE as a backend in Q1.
