### ISSUE TITLE
AttributeError: module 'torch_mlir._mlir_libs._mlir' has no attribute 'ir'

### ISSUE THREAD

**Issue by noahchalifour** [llvm/torch-mlir#653]
I am trying to use the python binding in my code but I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/model_server.py", line 6, in <module>
    from shark_runner import shark_inference
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/shark_runner.py", line 2, in <module>
    from torch_mlir.dialects.torch.importer.jit_ir import ClassAnnotator, ModuleBuilder
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/build/cmake_build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/torch/__init__.py", line 6, in <module>
    from .._torch_ops_gen import *
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/build/cmake_build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/_torch_ops_gen.py", line 4, in <module>
    from ._ods_common import _cext as _ods_cext
  File "/Users/noahchalifour/Code/noahchalifour/AI_TEXT_EDITOR_4250/ai-src/torch-mlir/build/cmake_build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/dialects/_ods_common.py", line 128, in <module>
    arg: _Union[_cext.ir.OpView, _cext.ir.Operation, _cext.ir.Value, _cext.ir.OpResultList]
AttributeError: module 'torch_mlir._mlir_libs._mlir' has no attribute 'ir'
```

When I look in the path `torch-mlir/build/cmake_build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/_mlir` I can see a file named `ir.pyi` Which I think is what its trying to access, so not sure what's wrong.

The code I am using is: (from https://github.com/NodLabs/shark-samples/blob/main/examples/shark_runner.py)

```
import torch
from torch_mlir.dialects.torch.importer.jit_ir import ClassAnnotator, ModuleBuilder
from torch_mlir_e2e_test.torchscript.annotations import (
    extract_serializable_annotations,
    apply_serializable_annotations,
)

from torch_mlir.passmanager import PassManager
from torch_mlir_e2e_test.linalg_on_tensors_backends.abc import LinalgOnTensorsBackend
from torch_mlir_e2e_test.torchscript.configs import LinalgOnTensorsBackendTestConfig
from torch_mlir_e2e_test.torchscript.annotations import annotate_args, export
from torch_mlir_e2e_test.torchscript.framework import (
    SerializableTest,
    generate_golden_trace,
)
from iree import runtime as ireert
import iree.compiler as ireec
import numpy as np
import os
import sys
import pickle
import io


def getTracedRecursiveScriptModule(module, input, dynamic):
    input_shape = list(input.shape)
    if dynamic:
        input_shape = [-1 for i in range(len(input.shape))]

    traced_module = torch.jit.trace_module(module, {"forward": input})
    script_module = traced_module._actual_script_module
    export(script_module.forward)
    annotate_args_decorator = annotate_args(
        [
            None,
            (input_shape, input.dtype, True),
        ]
    )
    annotate_args_decorator(script_module.forward)
    return script_module


def get_serialized_test(model):
    module = torch.jit.script(model)
    torchscript_module_bytes = module.save_to_buffer(
        {"annotations.pkl": pickle.dumps(extract_serializable_annotations(module))}
    )
    serializable_test = SerializableTest(
        unique_name="", program=torchscript_module_bytes, trace=None
    )
    _extra_files = {"annotations.pkl": ""}
    module = torch.jit.load(
        io.BytesIO(serializable_test.program), _extra_files=_extra_files
    )
    # Load the pickled annotations.
    annotations = pickle.loads(_extra_files["annotations.pkl"])
    apply_serializable_annotations(module, annotations)
    return module


# shark_inference takes torch.nn.module, input, and device, extracts torchscript,
# runs the torch-mlir linalg on tensors backend and finally runs via iree stack.
def shark_inference(module, input, device="cpu", dynamic=False, jit_trace=False):

    if jit_trace:
        module = getTracedRecursiveScriptModule(module, input, dynamic)
        module = get_serialized_test(module)
    else:
        module = torch.jit.script(module)

    input_shape = list(input.shape)
    if dynamic:
        input_shape = [-1 for i in range(len(input.shape))]

    mb = ModuleBuilder()
    class_annotator = ClassAnnotator()
    iree_device = {"cpu": "dylib", "gpu": "cuda", "vulkan": "vulkan"}
    class_annotator.exportNone(module._c._type())
    class_annotator.exportPath(module._c._type(), ["forward"])
    class_annotator.annotateArgs(
        module._c._type(),
        ["forward"],
        [
            None,
            (input_shape, input.dtype, True),
        ],
    )
    mb.import_module(module._c, class_annotator)

    with mb.module.context:
        pm = PassManager.parse(
            "torchscript-module-to-torch-backend-pipeline,torch-backend-to-linalg-on-tensors-backend-pipeline"
        )
        pm.run(mb.module)

    flatbuffer_blob = ireec.compile_str(
        str(mb.module), target_backends=[iree_device[device]]
    )
    vm_module = ireert.VmModule.from_flatbuffer(flatbuffer_blob)
    tracer = ireert.Tracer(os.getcwd())
    config = ireert.Config(iree_device[device], tracer)
    ctx = ireert.SystemContext(config=config)
    ctx.add_vm_module(vm_module)
    ModuleCompiled = ctx.modules.module["forward"]
    result = ModuleCompiled(input.numpy())
    result_numpy = np.asarray(result, dtype=np.float32)
    result_copy = np.copy(result_numpy)
    return result_copy
```

Any help would be appreciated.

**Comment by silvasean** [comment]
This is an issue with the torch-mlir build/install. Can you explain how you built/installed Torch-MLIR?

**Comment by noahchalifour** [comment]
@silvasean I used this command to build it:

```
CMAKE_GENERATOR=Ninja \
    TORCH_MLIR_CMAKE_BUILD_DIR=build/cmake_build \
    python setup.py bdist_wheel
```

And then to use it in my other virtual environment I use:

```
PYTHONPATH=`pwd`/torch-mlir/build/cmake_build/tools/torch-mlir/python_packages/torch_mlir:`pwd`/torch-mlir/examples
```

**Comment by noahchalifour** [comment]
Turns out by deleting the build and re-building using the `build_tools/build_python_wheels.sh` script solved this issue
