### ISSUE TITLE
OSX M1 Quantization Test Failed

### ISSUE THREAD

**Issue by powderluv** [llvm/torch-mlir#758]
```
[4/5] Running the torch-mlir regression tests
FAIL: TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py (71 of 88)
******************** TEST 'TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py' FAILED ********************
Script:
--
: 'RUN: at line 10';   /Users/anush/miniforge3/bin/python3.9 /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py | /Users/anush/github/torch-mlir/build/bin/torch-mlir-opt | FileCheck /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py
--
Exit Code: 1

Command Output (stderr):
--
Traceback (most recent call last):
  File "/Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py", line 38, in <module>
    test_module = TestModule()
  File "/Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py", line 17, in __init__
    self.linear = torch.nn.quantized.Linear(5, 2, dtype=torch.qint8)
  File "/Users/anush/miniforge3/lib/python3.9/site-packages/torch/nn/quantized/modules/linear.py", line 144, in __init__
    self._packed_params = LinearPackedParams(dtype)
  File "/Users/anush/miniforge3/lib/python3.9/site-packages/torch/nn/quantized/modules/linear.py", line 22, in __init__
    self.set_weight_bias(wq, None)
  File "/Users/anush/miniforge3/lib/python3.9/site-packages/torch/nn/quantized/modules/linear.py", line 27, in set_weight_bias
    self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
  File "/Users/anush/miniforge3/lib/python3.9/site-packages/torch/_ops.py", line 142, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
/Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py:22:11: error: CHECK: expected string not found in input
 # CHECK: %[[SCALE:.*]] = torch.constant.float
          ^
<stdin>:1:1: note: scanning from here
module {
^

Input file: <stdin>
Check file: /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py

-dump-input=help explains the following input dump.

Input was:
<<<<<<
          1: module { 
check:22     X~~~~~~~~ error: no match found
          2: } 
check:22     ~~
          3:  
check:22     ~
>>>>>>

--

********************
********************
Failed Tests (1):
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py


Testing Time: 5.52s
  Passed: 87
  Failed:  1
FAILED: tools/torch-mlir/test/CMakeFiles/check-torch-mlir /Users/anush/github/torch-mlir/build/tools/torch-mlir/test/CMakeFiles/check-torch-mlir 

```

**Comment by powderluv** [comment]
looks like an upstream FBGEMM issue on M1. Trying to use the qnnpack backend causes a different error 

````
FAIL: TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py (29 of 88)
******************** TEST 'TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py' FAILED ********************
Script:
--
: 'RUN: at line 10';   /Users/anush/miniforge3/bin/python3.9 /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py | /Users/anush/github/torch-mlir/build/bin/torch-mlir-opt | FileCheck /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py
--
Exit Code: 1

Command Output (stderr):
--
[W TensorImpl.h:1336] Warning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (function operator())
/Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py:33:11: error: CHECK: expected string not found in input
 # CHECK: %[[LINEAR_PARAMS_NO_BIAS:.*]] = torch.linear_params.create %{{[^,]*}} : !torch.tensor<[2,6],!torch.qint8>
          ^
<stdin>:116:100: note: scanning from here
 %3 = torch.linear_params.create %1, %2 : !torch.tensor<[2,5],!torch.qint8>, !torch.tensor<[2],f32>
                                                                                                   ^
<stdin>:136:2: note: possible intended match here
 %9 = torch.linear_params.create %7, %8 : !torch.tensor<[2,6],!torch.qint8>, !torch.tensor<[2],f32>
 ^

Input file: <stdin>
Check file: /Users/anush/github/torch-mlir/test/python/importer/jit_ir/ivalue_import/quantization.py

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
          111:  } 
          112:  %int12 = torch.constant.int 12 
          113:  %0 = torch.tensor.literal(dense<[[0, 0, 0, 0, 0], [0, 0, 0, -64, 75]]> : tensor<2x5xsi8>) : !torch.tensor<[2,5],si8> 
          114:  %1 = torch.per_tensor_affine.create %0, %float1.000000e00, %int0 : !torch.tensor<[2,5],si8>, !torch.float, !torch.int -> !torch.tensor<[2,5],!torch.qint8> 
          115:  %2 = torch.tensor.literal(dense<0.000000e+00> : tensor<2xf32>) : !torch.tensor<[2],f32> 
          116:  %3 = torch.linear_params.create %1, %2 : !torch.tensor<[2,5],!torch.qint8>, !torch.tensor<[2],f32> 
check:33'0                                                                                                        X error: no match found
          117:  %4 = torch.nn_module { 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~
          118:  torch.slot "training", %true : !torch.bool 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          119:  torch.slot "_is_full_backward_hook", %none : !torch.none 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          120:  torch.slot "dtype", %int12 : !torch.int 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          121:  torch.slot "_packed_params", %3 : !torch.LinearParams 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
          131:  } : !torch.nn.Module<"__torch__.torch.nn.quantized.modules.linear.Linear"> 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          132:  %int6 = torch.constant.int 6 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          133:  %6 = torch.tensor.literal(dense<[[-80, 46, 88, 3, 1, 0], [0, 0, -80, -87, 72, 3]]> : tensor<2x6xsi8>) : !torch.tensor<[2,6],si8> 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          134:  %7 = torch.per_tensor_affine.create %6, %float1.000000e00, %int0 : !torch.tensor<[2,6],si8>, !torch.float, !torch.int -> !torch.tensor<[2,6],!torch.qint8> 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          135:  %8 = torch.tensor.literal(dense<0.000000e+00> : tensor<2xf32>) : !torch.tensor<[2],f32> 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          136:  %9 = torch.linear_params.create %7, %8 : !torch.tensor<[2,6],!torch.qint8>, !torch.tensor<[2],f32> 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:33'1      ?                                                                                                   possible intended match
          137:  %10 = torch.nn_module { 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~
          138:  torch.slot "training", %true : !torch.bool 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          139:  torch.slot "_is_full_backward_hook", %none : !torch.none 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          140:  torch.slot "dtype", %int12 : !torch.int 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          141:  torch.slot "_packed_params", %9 : !torch.LinearParams 
check:33'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
            .
>>>>>>

--

********************
********************
Failed Tests (1):
  TORCH_MLIR :: python/importer/jit_ir/ivalue_import/quantization.py


Testing Time: 3.77s
  Passed: 87
  Failed:  1
FAILED: tools/torch-mlir/test/CMakeFiles/check-torch-mlir /Users/anush/github/torch-mlir/build/tools/torch-mlir/test/CMakeFiles/check-torch-mlir 
cd /Users/anush/github/torch-mlir/build/tools/torch-mlir/test && /Users/anush/miniforge3/bin/python3.9 /Users/anush/github/torch-mlir/build/./bin/llvm-lit -sv /Users/anush/github/torch-mlir/build/tools/torch-mlir/test
ninja: build stopped: subcommand failed.
````

**Comment by nirvedhmeshram** [comment]
I think this maybe an issue with torchvision, on linux side we are using
```
Requirement already satisfied: torchvision in ./mlir_venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.13.0.dev20220414+cpu)
```
But on mac the latest available is 0.12.0

**Comment by powderluv** [comment]
Ah yeah. I think I ran into having to install it from source for the M1.

**Comment by powderluv** [comment]
not seen anymore. closing it out.
